"""Backend adapter specs and launch-script generation.

These adapters do not replace the orchestrator.  They make backend choices
explicit and produce reproducible launch commands for local, Accelerate,
DeepSpeed, Megatron-style, and Colossal-style execution paths.
"""
import json
import os
from dataclasses import asdict, dataclass, field
from typing import Dict, List, Optional


@dataclass
class LaunchPlan:
    backend: str
    command: List[str]
    env: Dict[str, str] = field(default_factory=dict)
    notes: List[str] = field(default_factory=list)
    script_path: Optional[str] = None

    def to_dict(self) -> Dict:
        return asdict(self)


class BackendAdapterRegistry:
    """Create launch plans for SaddleLLM and external-style backends."""

    @staticmethod
    def create_launch_plan(
        config_path: str,
        backend: str = "auto",
        num_gpus: int = 1,
        num_nodes: int = 1,
        backend_plan_path: Optional[str] = None,
    ) -> LaunchPlan:
        if backend == "auto":
            backend = BackendAdapterRegistry._infer_backend(config_path, backend_plan_path)
        backend = BackendAdapterRegistry._normalize_backend_name(backend)
        if int(num_gpus) < 1 or int(num_nodes) < 1:
            raise ValueError("num_gpus and num_nodes must be >= 1")

        if backend in {"single", "torch_ddp", "torch_fsdp", "deepspeed_zero2", "deepspeed_zero3"}:
            return BackendAdapterRegistry._accelerate_plan(
                config_path, backend, num_gpus, num_nodes
            )
        if backend in {"hybrid_parallel", "moe_hybrid_parallel"}:
            raise NotImplementedError(
                "Hybrid TP/PP/CP/EP launch requires a runtime adapter; "
                "no executable fallback is generated"
            )
        raise ValueError(f"Unknown backend: {backend}")

    @staticmethod
    def _normalize_backend_name(backend: str) -> str:
        aliases = {
            "ddp": "torch_ddp",
            "fsdp": "torch_fsdp",
            "deepspeed": "deepspeed_zero2",
        }
        return aliases.get(backend, backend)

    @staticmethod
    def save_launch_script(plan: LaunchPlan, path: str) -> str:
        os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
        lines = ["# Auto-generated by SaddleLLM", "$ErrorActionPreference = 'Stop'", ""]
        for key, value in plan.env.items():
            lines.append(f"$env:{key} = '{value}'")
        cmd = " ".join(BackendAdapterRegistry._quote(arg) for arg in plan.command)
        lines.append(cmd)
        with open(path, "w", encoding="utf-8") as f:
            f.write("\n".join(lines) + "\n")
        plan.script_path = path
        return path

    @staticmethod
    def save_launch_plan(plan: LaunchPlan, path: str) -> str:
        os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
        with open(path, "w", encoding="utf-8") as f:
            json.dump(plan.to_dict(), f, ensure_ascii=False, indent=2)
        return path

    @staticmethod
    def _accelerate_plan(
        config_path: str, backend: str, num_gpus: int, num_nodes: int = 1
    ) -> LaunchPlan:
        if backend == "single":
            return LaunchPlan(
                backend="single",
                command=["python", "-m", "saddle_llm.cli", "train", config_path],
                notes=["Single-process launch through TrainingOrchestrator."],
            )
        if num_gpus * num_nodes < 2:
            raise ValueError(f"backend={backend!r} requires at least 2 processes")
        command = [
            "accelerate",
            "launch",
            "--num_processes",
            str(num_gpus),
            "-m",
            "saddle_llm.cli",
            "train",
            config_path,
        ]
        if backend == "torch_fsdp":
            command[2:2] = ["--use_fsdp"]
        elif backend.startswith("deepspeed"):
            command[2:2] = ["--use_deepspeed"]
        if num_nodes > 1:
            machine_rank = os.environ.get("MACHINE_RANK")
            main_ip = os.environ.get("MAIN_PROCESS_IP")
            main_port = os.environ.get("MAIN_PROCESS_PORT", "29500")
            if machine_rank is None or main_ip is None:
                raise ValueError(
                    "multi-node launch requires MACHINE_RANK and MAIN_PROCESS_IP environment variables"
                )
            command[2:2] = [
                "--num_machines", str(num_nodes),
                "--machine_rank", machine_rank,
                "--main_process_ip", main_ip,
                "--main_process_port", main_port,
            ]
        notes = [f"Uses Accelerate with backend strategy hint: {backend}."]
        if backend.startswith("deepspeed"):
            notes.append("Make sure the config contains a DeepSpeed strategy or config path.")
        return LaunchPlan(backend=backend, command=command, notes=notes)

    @staticmethod
    def _hybrid_plan(
        config_path: str,
        backend: str,
        num_gpus: int,
        backend_plan_path: Optional[str],
    ) -> LaunchPlan:
        notes = [
            "Hybrid TP/PP/CP/EP execution requires a Megatron/Colossal runtime adapter.",
            "This script is a handoff plan and uses SaddleLLM config as the source of truth.",
        ]
        command = [
            "torchrun",
            "--nproc_per_node",
            str(num_gpus),
            "-m",
            "saddle_llm.cli",
            "train",
            config_path,
        ]
        if backend_plan_path:
            notes.append(f"Backend plan: {backend_plan_path}")
        return LaunchPlan(backend=backend, command=command, notes=notes)

    @staticmethod
    def _infer_backend(config_path: str, backend_plan_path: Optional[str]) -> str:
        if backend_plan_path and os.path.exists(backend_plan_path):
            with open(backend_plan_path, "r", encoding="utf-8") as f:
                return json.load(f).get("plan", {}).get("backend", "single")
        try:
            with open(config_path, "r", encoding="utf-8") as f:
                if config_path.lower().endswith((".yaml", ".yml")):
                    import yaml
                    data = yaml.safe_load(f) or {}
                else:
                    data = json.load(f)
            return data.get("distributed", data.get("backend", {})).get("strategy", "single")
        except Exception:
            return "single"

    @staticmethod
    def _quote(value: str) -> str:
        if not value or any(ch.isspace() for ch in value):
            return "'" + value.replace("'", "''") + "'"
        return value
