__version__ = "2.32"
__all__ = [
    '__version__',
    # Loaders
    'unsloth_load_lora_model', 'transfomer_load_lora', 'src_mode_transformer_load',
    # LoRA
    'LoRATuner',
    # SFT / Fine-tuning
    'train_sft', 'train_full', 'PreferenceTrainer', 'PreferenceTrainConfig', 'train_preference',
    # Quantization / Pruning / Distillation
    'quantize_model', 'prune_model', 'distill_model',
    'run_large_model_operator', 'run_agent_operator', 'normalize_agent_config',
    # Data / Eval / Processing
    'balance_data', 'evaluate_llm', 'Evaluator', 'process_text',
    # v2.2.0: 完整训练体系
    'TokenizerTrainer', 'ModelRegistry', 'ArchitectureRegistry', 'ArchitectureSupport', 'DataPipeline',
    'TokenizerEvalResult', 'PretrainRunPlan',
    'DataMixPlanner', 'DataMixPlan', 'DataBucketPlan', 'ContaminationDetector', 'ContaminationReport',
    'PretrainEvalSuite', 'EvalTaskSpec', 'EvalSuiteResult',
    'PretrainReport', 'PretrainReportResult', 'ReportFinding',
    'PretrainExperimentRunner', 'PretrainExperimentConfig', 'ExperimentBundle', 'ExperimentRunManifest',
    'LLMTrainingFactory', 'FactoryConfig', 'FactoryStatus',
    'DatasetManifest', 'DatasetManifestEntry',
    'FactoryBackendPlanner', 'ParallelismPlan', 'TrainingBackendSpec',
    'TrainingRecipe', 'RecipeModelConfig', 'RecipeMethodConfig', 'RecipeDataConfig',
    'RecipeBackendConfig', 'RecipeTrainingConfig', 'RecipeEvalConfig', 'RecipeLoggingConfig',
    'RecipeMultimodalConfig', 'RecipeMOPDConfig', 'RecipeVLAConfig',
    'BackendAdapterRegistry', 'LaunchPlan',
    'DistributedRuntimeInfo', 'current_distributed_runtime',
    'validate_distributed_runtime', 'distributed_barrier',
    'ModelBlueprint', 'ModelBlueprintLab', 'AttentionBlueprint', 'FFNBlueprint',
    'ResidualBlueprint', 'LayerBlueprint', 'ObjectiveBlueprint',
    'VisionBlueprint', 'ProjectorBlueprint',
    'ModelComponentRegistry', 'SaddleModelBuilder',
    'SaddleModelConfig', 'SaddleForCausalLM', 'SaddleDecoderLayer', 'SaddleAttention',
    'SaddleSwiGLU', 'SaddleMoE', 'SaddleRMSNorm', 'SaddleCausalLMOutput', 'SaddleGenerationOutput',
    'is_saddle_checkpoint', 'load_causal_lm', 'load_model_and_tokenizer', 'SaddleTrainer',
    'ModelBackendCapabilities', 'ModelAdapter', 'SaddleModelAdapter',
    'HuggingFaceModelAdapter', 'get_model_adapter',
    'NativeSFTConfig', 'NativeDPOConfig', 'train_native_sft', 'train_native_dpo',
    'ModelMetricsExtractor', 'ModelMetricsCallback', 'ModelMetricSnapshot',
    'AttentionBackendRegistry', 'AttentionBackendSpec', 'list_attention_backends',
    'MultimodalConfig', 'MultimodalForCausalLM',
    'MultimodalDataAdapter', 'MultimodalSample', 'MultimodalAsset', 'MultimodalSegment',
    'normalize_multimodal_file',
    'ModalityCodecSpec', 'ModalityCodec', 'CallableModalityCodec', 'ModalityCodecRegistry',
    'TextConditionEncoder', 'HashTextConditionEncoder',
    'HuggingFaceTextConditionEncoder', 'build_text_condition_encoder',
    'RGBImageCodec', 'WAVResidualCodec', 'FrameVideoCodec',
    'register_builtin_media_codecs', 'MediaCacheBuildConfig',
    'ShardedNpzStore', 'build_media_cache',
    'LatentFlowConfig', 'ConditionalLatentFlowTransformer',
    'LatentFlowTrainingConfig', 'CachedLatentDataset', 'train_latent_flow',
    'save_latent_flow_checkpoint', 'load_latent_flow_checkpoint',
    'MusicCodeConfig', 'ConditionalMusicCodeTransformer',
    'MusicCodeTrainingConfig', 'CachedMusicCodeDataset', 'train_music_code',
    'save_music_code_checkpoint', 'load_music_code_checkpoint',
    'VideoLatentFlowConfig', 'ConditionalVideoLatentFlowTransformer',
    'VideoLatentFlowTrainingConfig', 'CachedVideoLatentDataset',
    'train_video_latent_flow', 'save_video_latent_flow_checkpoint',
    'load_video_latent_flow_checkpoint',
    'VLAActionSpace', 'VLAAction', 'VLASample', 'VLANormalizationReport',
    'VLACollatorConfig', 'VLAActionTokenizer', 'VLADataAdapter', 'VLADataset',
    'VLADataCollator', 'VLATrainingPlanner', 'normalize_vla_file', 'register_vla_action_tokens',
    'VLADataInspector', 'VLADataInspection', 'inspect_vla_data',
    'VLASFTConfig', 'train_vla_sft',
    'WorldModelConfig', 'RSSMState', 'WorldModelOutput', 'WorldModelImagination',
    'ObservationEncoder', 'ObservationDecoder', 'RSSMCell', 'WorldModel',
    'WorldModelDataError', 'WorldModelTrajectoryDataset',
    'load_world_model_trajectories', 'split_world_model_trajectories',
    'infer_world_model_dimensions',
    'WorldModelDataConfig', 'WorldModelTrainingConfig', 'WorldModelTrainer',
    'prepare_world_model_training', 'train_world_model_from_config', 'train_world_model',
    'CategoricalWorldModelConfig', 'CategoricalWorldModelOutput',
    'CategoricalRSSMCell', 'CategoricalWorldModel', 'symlog', 'symexp',
    'NATIVE_WORLD_MODEL_BACKENDS', 'normalize_world_model_backend',
    'create_world_model', 'load_world_model', 'list_world_model_backends',
    'WorldModelPlannerConfig', 'WorldModelActionEvaluation', 'WorldModelPlan',
    'WorldModelRuntime', 'run_world_model_inference',
    'OccupancyGrid', 'SpatialPlannerConfig', 'RouteCandidate', 'GridPathPlanner',
    'SpatialEntity', 'SpatialAnalysis', 'MapExtractionConfig',
    'TopDownMapExtractor', 'CallableSpatialAnalyzer', 'QwenVLSpatialAnalyzer',
    'SpatialPlanResult', 'SpatialObservationEncoder', 'SpatialBeliefMap',
    'SpatialTensorObservationEncoder', 'WorldModelRouteScorer', 'SpatialWorldModelCoordinator',
    'SpatialTrajectoryConfig', 'SpatialTrajectoryBuilder', 'generate_spatial_world_model_dataset',
    'SpatialSequenceConfig', 'SpatialSequenceTrajectoryBuilder', 'generate_spatial_sequence_dataset',
    'SpatialCEMPlannerConfig', 'SpatialCEMPlan', 'SpatialClosedLoopResult', 'SpatialClosedLoopPlanner',
    'evaluate_spatial_world_model',
    'save_spatial_plan_json', 'render_spatial_plan_html', 'render_spatial_plan_png',
    'save_occupancy_mask_png',
    'SpatialPlanRequest', 'SpatialStudioSettings', 'SpatialStudioService',
    'create_spatial_studio_app',
    'WorldAgentError', 'WorldAgentSettings', 'WorldObservation', 'WorldState',
    'WorldPlan', 'WorldSimulation', 'WorldFeedback', 'WorldAgentStore',
    'WorldAgentRuntime', 'WorldAnalyzeRequest', 'WorldPlanRequest',
    'WorldSimulationRequest', 'WorldFeedbackRequest', 'create_world_agent_app',
    'PostTrainingDataAdapter', 'NormalizationReport', 'normalize_post_training_record', 'normalize_post_training_file',
    'VisionBackboneConfig', 'VisionBackboneRegistry', 'list_vision_backbones',
    'MultimodalProjectorConfig', 'MultimodalProjectorFactory',
    'ModelExperimentPlanner', 'ModelExperimentConfig', 'ModelExperimentBundle', 'ModelExperimentRun',
    'DomainModelBuilder', 'DomainBuildConfig', 'DomainRecipe', 'list_domain_recipes',
    'DistributedConfig', 'TrainingOrchestrator',
    'TrainingDataInspector', 'TrainingDataInspection', 'inspect_training_data',
    'TrainingPlanEstimator', 'TrainingPlanEstimate', 'estimate_training_plan',
    'SimpleFlowCompiler',
    'TrainingConfigValidator', 'TrainingConfigValidation', 'validate_training_config',
    'EvaluationReleaseGate', 'ReleaseGateResult', 'evaluate_release_gate',
    'ModelExportRequest', 'ModelExportResult', 'ModelExporter', 'export_model',
    'InferenceServerSettings', 'LocalGenerationEngine', 'create_inference_app', 'load_inference_model',
    'SmokeTestRunner', 'SmokeTestResult', 'SmokeCommandResult', 'run_smoke_tests',
    'ExperimentTracker', 'BenchmarkRunner',
    'ScalingLawAnalyzer', 'CurriculumScheduler',
    # v2.3.0: 前沿架构 + 效率 + 对齐 + 实战训练
    'TrainingMonitor', 'DataMixer', 'GRPOConfig', 'GRPOTrainer',
    'RLScalingTrainer','RLScalingConfig', 'RolloutBuffer', 'RolloutSample', 'RolloutSegment',
    'RewardManager', 'TriageConfig', 'ActionRoleClassifier', 'TriageCreditAssigner', 'TriageRolloutProcessor',
    'TrainingStrategyAdvisor', 'FeasibilityReport', 'TrainingRoute', 'BudgetProfile',
    'PretrainStabilityCallback', 'StabilityConfig', 'StabilityEvent', 'CheckpointInspector',
    'DensePretrainer', 'init_weights_llama_style', 'init_weights_deepseek_style',
    # v2.4.0: OpenAI & Anthropic 前沿对齐技术
    'ConstitutionalAI', 'ProcessRewardModel', 'RejectionSampling',
    'FrontierAlignmentPipeline',
    # v2.5.0: 效果提升技术
    'EMA', 'EMACallback', 'SelfConsistency',
    'EvolInstruct', 'ModelSoup', 'InstructionBacktranslation',
    # v2.6.0: OpenAI/DeepSeek/Anthropic 独门技术
    'MultiTokenPredictionHead', 'MultiTokenPredictionLoss', 'add_mtp_to_model',
    'AuxLossFreeRouter', 'AuxLossFreeMoELayer',
    'IterativeAlignment', 'TestTimeCompute',
    'RLAIF', 'SLURPMixer', 'RoPEScaling', 'SparseAutoencoder',
    # v2.7.0: 通用蒸馏系统
    'TeacherInterface', 'DataDistiller', 'MultiTeacherDistiller',
    'CapabilityDistiller', 'AutoDistiller', 'DistillConfig',
    'OnPolicyTeacherSpec', 'TeacherPolicySignal', 'MOPDConfig', 'MultiTeacherOnPolicyDistiller',
    # 简易接口 + 数据目录 + Chat UI + 部署 + 轻量化 + 快速蒸馏
    'easy', 'DataCatalog', 'DataQualityClassifier',
    'ChatUI', 'Deploy', 'Lightweight',
    'RapidDistill', 'SmartRouter', 'ParallelAPICaller', 'TEACHER_PROFILES',
    'DOWNLOADABLE_TEACHERS', 'ModelDownloader', 'LocalTeacherPool', 'quick_local_distill',
    # 安全生成 & 反车轱辘话
    'SafeGenerate', 'AntiRepeatGenerator', 'OutputSafetyFilter', 'filter_toxic_texts',
    # 训练工具
    'check_environment', 'TrainingDiagnostics', 'TrainingReportCard',
    'EarlyStopping', 'auto_train_best_small_model',
]

import importlib

# Public objects are resolved by ``__getattr__`` below.  Keeping package import
# lightweight is important for inference-only callers: importing one provider
# adapter must not initialize Torch, Triton, training backends, or vision stacks.

_LAZY_IMPORT_MAP = {
    # 原有
    'LoRATuner':                    ('.LoRATuner', 'LoRATuner'),
    'train_sft':                    ('.PeftSFTTrainer', 'train_model'),
    'train_full':                   ('.TRLFullFineTuner', 'train_model'),
    'PreferenceTrainer':            ('.Preference', 'PreferenceTrainer'),
    'PreferenceTrainConfig':        ('.Preference', 'PreferenceTrainConfig'),
    'train_preference':             ('.Preference', 'train_preference'),
    'quantize_model':               ('.ModelQuantizer', 'ModelQuantizer'),
    'prune_model':                  ('.ModelPruner', 'ModelPruner'),
    'distill_model':                ('.DistillationTrainer', 'DistillationTrainer'),
    'run_large_model_operator':     ('.RealWorldOperators', 'run_large_model_operator'),
    'run_agent_operator':           ('.AgentOperators', 'run_agent_operator'),
    'normalize_agent_config':       ('.AgentOperators', 'normalize_agent_config'),
    'balance_data':                 ('.DataBalance', 'BalancedPretrainer'),
    'evaluate_llm':                 ('.LLModelEvalute', 'Evaluator'),
    'Evaluator':                    ('.LLModelEvalute', 'Evaluator'),
    'process_text':                 ('.TextProcess', 'TextCleaner'),
    'unsloth_load_lora_model':      ('.load_model', 'unsloth_load_lora_model'),
    'transfomer_load_lora':         ('.load_model', 'transfomer_load_lora'),
    'src_mode_transformer_load':    ('.load_model', 'src_mode_transformer_load'),
    # 新增 v2.2.0
    'TokenizerTrainer':             ('.TokenizerTrainer', 'TokenizerTrainer'),
    'TokenizerEvalResult':          ('.TokenizerTrainer', 'TokenizerEvalResult'),
    'ModelRegistry':                ('.ModelRegistry', 'ModelRegistry'),
    'ArchitectureRegistry':         ('.Architecture', 'ArchitectureRegistry'),
    'ArchitectureSupport':          ('.Architecture', 'ArchitectureSupport'),
    'DataPipeline':                 ('.DataPipeline', 'DataPipeline'),
    'DataMixPlanner':               ('.DataStrategy', 'DataMixPlanner'),
    'DataMixPlan':                  ('.DataStrategy', 'DataMixPlan'),
    'DataBucketPlan':               ('.DataStrategy', 'DataBucketPlan'),
    'ContaminationDetector':        ('.DataStrategy', 'ContaminationDetector'),
    'ContaminationReport':          ('.DataStrategy', 'ContaminationReport'),
    'PretrainEvalSuite':            ('.PretrainEvalSuite', 'PretrainEvalSuite'),
    'EvalTaskSpec':                 ('.PretrainEvalSuite', 'EvalTaskSpec'),
    'EvalSuiteResult':              ('.PretrainEvalSuite', 'EvalSuiteResult'),
    'PretrainReport':               ('.PretrainReport', 'PretrainReport'),
    'PretrainReportResult':         ('.PretrainReport', 'PretrainReportResult'),
    'ReportFinding':                ('.PretrainReport', 'ReportFinding'),
    'PretrainExperimentRunner':     ('.PretrainExperimentRunner', 'PretrainExperimentRunner'),
    'PretrainExperimentConfig':     ('.PretrainExperimentRunner', 'PretrainExperimentConfig'),
    'ExperimentBundle':             ('.PretrainExperimentRunner', 'ExperimentBundle'),
    'ExperimentRunManifest':        ('.PretrainExperimentRunner', 'ExperimentRunManifest'),
    'LLMTrainingFactory':           ('.TrainingFactory', 'LLMTrainingFactory'),
    'FactoryConfig':                ('.TrainingFactory', 'FactoryConfig'),
    'FactoryStatus':                ('.TrainingFactory', 'FactoryStatus'),
    'DatasetManifest':              ('.DatasetManifest', 'DatasetManifest'),
    'DatasetManifestEntry':         ('.DatasetManifest', 'DatasetManifestEntry'),
    'FactoryBackendPlanner':        ('.FactoryBackendPlanner', 'FactoryBackendPlanner'),
    'ParallelismPlan':              ('.FactoryBackendPlanner', 'ParallelismPlan'),
    'TrainingBackendSpec':          ('.FactoryBackendPlanner', 'TrainingBackendSpec'),
    'TrainingRecipe':               ('.TrainingRecipe', 'TrainingRecipe'),
    'RecipeModelConfig':            ('.TrainingRecipe', 'RecipeModelConfig'),
    'RecipeMethodConfig':           ('.TrainingRecipe', 'RecipeMethodConfig'),
    'RecipeDataConfig':             ('.TrainingRecipe', 'RecipeDataConfig'),
    'RecipeBackendConfig':          ('.TrainingRecipe', 'RecipeBackendConfig'),
    'RecipeTrainingConfig':         ('.TrainingRecipe', 'RecipeTrainingConfig'),
    'RecipeEvalConfig':             ('.TrainingRecipe', 'RecipeEvalConfig'),
    'RecipeLoggingConfig':          ('.TrainingRecipe', 'RecipeLoggingConfig'),
    'RecipeMultimodalConfig':       ('.TrainingRecipe', 'RecipeMultimodalConfig'),
    'RecipeMOPDConfig':             ('.TrainingRecipe', 'RecipeMOPDConfig'),
    'RecipeVLAConfig':              ('.TrainingRecipe', 'RecipeVLAConfig'),
    'BackendAdapterRegistry':       ('.BackendAdapters', 'BackendAdapterRegistry'),
    'LaunchPlan':                   ('.BackendAdapters', 'LaunchPlan'),
    'DistributedRuntimeInfo':       ('.DistributedRuntime', 'DistributedRuntimeInfo'),
    'current_distributed_runtime':  ('.DistributedRuntime', 'current_distributed_runtime'),
    'validate_distributed_runtime': ('.DistributedRuntime', 'validate_distributed_runtime'),
    'distributed_barrier':          ('.DistributedRuntime', 'distributed_barrier'),
    'ModelBlueprint':               ('.ModelBlueprint', 'ModelBlueprint'),
    'ModelBlueprintLab':            ('.ModelBlueprint', 'ModelBlueprintLab'),
    'AttentionBlueprint':           ('.ModelBlueprint', 'AttentionBlueprint'),
    'FFNBlueprint':                 ('.ModelBlueprint', 'FFNBlueprint'),
    'ResidualBlueprint':            ('.ModelBlueprint', 'ResidualBlueprint'),
    'LayerBlueprint':               ('.ModelBlueprint', 'LayerBlueprint'),
    'ObjectiveBlueprint':           ('.ModelBlueprint', 'ObjectiveBlueprint'),
    'VisionBlueprint':              ('.ModelBlueprint', 'VisionBlueprint'),
    'ProjectorBlueprint':           ('.ModelBlueprint', 'ProjectorBlueprint'),
    'ModelComponentRegistry':       ('.ModelBuilder', 'ModelComponentRegistry'),
    'SaddleModelBuilder':           ('.ModelBuilder', 'SaddleModelBuilder'),
    'SaddleModelConfig':            ('.SaddleModeling', 'SaddleModelConfig'),
    'SaddleForCausalLM':            ('.SaddleModeling', 'SaddleForCausalLM'),
    'SaddleDecoderLayer':           ('.SaddleModeling', 'SaddleDecoderLayer'),
    'SaddleAttention':              ('.SaddleModeling', 'SaddleAttention'),
    'SaddleSwiGLU':                 ('.SaddleModeling', 'SaddleSwiGLU'),
    'SaddleMoE':                    ('.SaddleModeling', 'SaddleMoE'),
    'SaddleRMSNorm':                ('.SaddleModeling', 'SaddleRMSNorm'),
    'SaddleCausalLMOutput':         ('.SaddleModeling', 'SaddleCausalLMOutput'),
    'SaddleGenerationOutput':       ('.SaddleModeling', 'SaddleGenerationOutput'),
    'is_saddle_checkpoint':         ('.ModelLoader', 'is_saddle_checkpoint'),
    'load_causal_lm':               ('.ModelLoader', 'load_causal_lm'),
    'load_model_and_tokenizer':     ('.ModelLoader', 'load_model_and_tokenizer'),
    'SaddleTrainer':                ('.NativeTrainer', 'SaddleTrainer'),
    'ModelBackendCapabilities':     ('.ModelAdapter', 'ModelBackendCapabilities'),
    'ModelAdapter':                 ('.ModelAdapter', 'ModelAdapter'),
    'SaddleModelAdapter':           ('.ModelAdapter', 'SaddleModelAdapter'),
    'HuggingFaceModelAdapter':      ('.ModelAdapter', 'HuggingFaceModelAdapter'),
    'get_model_adapter':            ('.ModelAdapter', 'get_model_adapter'),
    'NativeSFTConfig':              ('.NativePostTraining', 'NativeSFTConfig'),
    'NativeDPOConfig':              ('.NativePostTraining', 'NativeDPOConfig'),
    'train_native_sft':             ('.NativePostTraining', 'train_native_sft'),
    'train_native_dpo':             ('.NativePostTraining', 'train_native_dpo'),
    'ModelMetricsExtractor':        ('.ModelMetrics', 'ModelMetricsExtractor'),
    'ModelMetricsCallback':         ('.ModelMetrics', 'ModelMetricsCallback'),
    'ModelMetricSnapshot':          ('.ModelMetrics', 'ModelMetricSnapshot'),
    'AttentionBackendRegistry':     ('.OperatorBackends', 'AttentionBackendRegistry'),
    'AttentionBackendSpec':         ('.OperatorBackends', 'AttentionBackendSpec'),
    'list_attention_backends':      ('.OperatorBackends', 'list_attention_backends'),
    'MultimodalConfig':             ('.MultimodalModeling', 'MultimodalConfig'),
    'MultimodalForCausalLM':        ('.MultimodalModeling', 'MultimodalForCausalLM'),
    'MultimodalDataAdapter':        ('.MultimodalData', 'MultimodalDataAdapter'),
    'MultimodalSample':             ('.MultimodalData', 'MultimodalSample'),
    'MultimodalAsset':              ('.MultimodalData', 'MultimodalAsset'),
    'MultimodalSegment':            ('.MultimodalData', 'MultimodalSegment'),
    'normalize_multimodal_file':    ('.MultimodalData', 'normalize_multimodal_file'),
    'ModalityCodecSpec':            ('.ModalityCodec', 'ModalityCodecSpec'),
    'ModalityCodec':                ('.ModalityCodec', 'ModalityCodec'),
    'CallableModalityCodec':        ('.ModalityCodec', 'CallableModalityCodec'),
    'ModalityCodecRegistry':        ('.ModalityCodec', 'ModalityCodecRegistry'),
    'TextConditionEncoder':         ('.BuiltinMediaCodecs', 'TextConditionEncoder'),
    'HashTextConditionEncoder':     ('.BuiltinMediaCodecs', 'HashTextConditionEncoder'),
    'HuggingFaceTextConditionEncoder': ('.BuiltinMediaCodecs', 'HuggingFaceTextConditionEncoder'),
    'build_text_condition_encoder': ('.BuiltinMediaCodecs', 'build_text_condition_encoder'),
    'RGBImageCodec':                ('.BuiltinMediaCodecs', 'RGBImageCodec'),
    'WAVResidualCodec':             ('.BuiltinMediaCodecs', 'WAVResidualCodec'),
    'FrameVideoCodec':              ('.BuiltinMediaCodecs', 'FrameVideoCodec'),
    'register_builtin_media_codecs': ('.BuiltinMediaCodecs', 'register_builtin_media_codecs'),
    'MediaCacheBuildConfig':        ('.MediaCache', 'MediaCacheBuildConfig'),
    'ShardedNpzStore':              ('.MediaCache', 'ShardedNpzStore'),
    'build_media_cache':            ('.MediaCache', 'build_media_cache'),
    'LatentFlowConfig':             ('.LatentFlowModel', 'LatentFlowConfig'),
    'ConditionalLatentFlowTransformer': ('.LatentFlowModel', 'ConditionalLatentFlowTransformer'),
    'LatentFlowTrainingConfig':       ('.LatentFlowTrainer', 'LatentFlowTrainingConfig'),
    'CachedLatentDataset':            ('.LatentFlowTrainer', 'CachedLatentDataset'),
    'train_latent_flow':              ('.LatentFlowTrainer', 'train_latent_flow'),
    'save_latent_flow_checkpoint':    ('.LatentFlowTrainer', 'save_latent_flow_checkpoint'),
    'load_latent_flow_checkpoint':    ('.LatentFlowTrainer', 'load_latent_flow_checkpoint'),
    'MusicCodeConfig':              ('.MusicCodeModel', 'MusicCodeConfig'),
    'ConditionalMusicCodeTransformer': ('.MusicCodeModel', 'ConditionalMusicCodeTransformer'),
    'MusicCodeTrainingConfig':       ('.MusicCodeTrainer', 'MusicCodeTrainingConfig'),
    'CachedMusicCodeDataset':        ('.MusicCodeTrainer', 'CachedMusicCodeDataset'),
    'train_music_code':              ('.MusicCodeTrainer', 'train_music_code'),
    'save_music_code_checkpoint':    ('.MusicCodeTrainer', 'save_music_code_checkpoint'),
    'load_music_code_checkpoint':    ('.MusicCodeTrainer', 'load_music_code_checkpoint'),
    'VideoLatentFlowConfig':         ('.VideoLatentFlowModel', 'VideoLatentFlowConfig'),
    'ConditionalVideoLatentFlowTransformer': ('.VideoLatentFlowModel', 'ConditionalVideoLatentFlowTransformer'),
    'VideoLatentFlowTrainingConfig': ('.VideoLatentFlowTrainer', 'VideoLatentFlowTrainingConfig'),
    'CachedVideoLatentDataset':      ('.VideoLatentFlowTrainer', 'CachedVideoLatentDataset'),
    'train_video_latent_flow':       ('.VideoLatentFlowTrainer', 'train_video_latent_flow'),
    'save_video_latent_flow_checkpoint': ('.VideoLatentFlowTrainer', 'save_video_latent_flow_checkpoint'),
    'load_video_latent_flow_checkpoint': ('.VideoLatentFlowTrainer', 'load_video_latent_flow_checkpoint'),
    'VLAActionSpace':               ('.VLA', 'VLAActionSpace'),
    'VLAAction':                    ('.VLA', 'VLAAction'),
    'VLASample':                    ('.VLA', 'VLASample'),
    'VLANormalizationReport':       ('.VLA', 'VLANormalizationReport'),
    'VLACollatorConfig':            ('.VLA', 'VLACollatorConfig'),
    'VLAActionTokenizer':           ('.VLA', 'VLAActionTokenizer'),
    'VLADataAdapter':               ('.VLA', 'VLADataAdapter'),
    'VLADataset':                   ('.VLA', 'VLADataset'),
    'VLADataCollator':              ('.VLA', 'VLADataCollator'),
    'VLATrainingPlanner':           ('.VLA', 'VLATrainingPlanner'),
    'normalize_vla_file':           ('.VLA', 'normalize_vla_file'),
    'register_vla_action_tokens':   ('.VLA', 'register_vla_action_tokens'),
    'VLADataInspector':             ('.VLADataInspector', 'VLADataInspector'),
    'VLADataInspection':            ('.VLADataInspector', 'VLADataInspection'),
    'inspect_vla_data':             ('.VLADataInspector', 'inspect_vla_data'),
    'VLASFTConfig':                 ('.VLATrainer', 'VLASFTConfig'),
    'train_vla_sft':                ('.VLATrainer', 'train_vla_sft'),
    'WorldModelConfig':             ('._WorldModel', 'WorldModelConfig'),
    'RSSMState':                    ('._WorldModel', 'RSSMState'),
    'WorldModelOutput':             ('._WorldModel', 'WorldModelOutput'),
    'WorldModelImagination':        ('._WorldModel', 'WorldModelImagination'),
    'ObservationEncoder':           ('._WorldModel', 'ObservationEncoder'),
    'ObservationDecoder':           ('._WorldModel', 'ObservationDecoder'),
    'RSSMCell':                     ('._WorldModel', 'RSSMCell'),
    'WorldModel':                   ('._WorldModel', 'WorldModel'),
    'WorldModelDataError':          ('.WorldModelData', 'WorldModelDataError'),
    'WorldModelTrajectoryDataset':  ('.WorldModelData', 'WorldModelTrajectoryDataset'),
    'load_world_model_trajectories': ('.WorldModelData', 'load_world_model_trajectories'),
    'split_world_model_trajectories': ('.WorldModelData', 'split_world_model_trajectories'),
    'infer_world_model_dimensions': ('.WorldModelData', 'infer_world_model_dimensions'),
    'WorldModelDataConfig':         ('._WorldModelTrainer', 'WorldModelDataConfig'),
    'WorldModelTrainingConfig':     ('._WorldModelTrainer', 'WorldModelTrainingConfig'),
    'WorldModelTrainer':            ('._WorldModelTrainer', 'WorldModelTrainer'),
    'prepare_world_model_training': ('._WorldModelTrainer', 'prepare_world_model_training'),
    'train_world_model_from_config': ('._WorldModelTrainer', 'train_world_model_from_config'),
    'train_world_model':            ('._WorldModelTrainer', 'train_world_model'),
    'CategoricalWorldModelConfig':  ('._CategoricalWorldModel', 'CategoricalWorldModelConfig'),
    'CategoricalWorldModelOutput':  ('._CategoricalWorldModel', 'CategoricalWorldModelOutput'),
    'CategoricalRSSMCell':          ('._CategoricalWorldModel', 'CategoricalRSSMCell'),
    'CategoricalWorldModel':        ('._CategoricalWorldModel', 'CategoricalWorldModel'),
    'symlog':                       ('._CategoricalWorldModel', 'symlog'),
    'symexp':                       ('._CategoricalWorldModel', 'symexp'),
    'NATIVE_WORLD_MODEL_BACKENDS': ('.WorldModelBackends', 'NATIVE_WORLD_MODEL_BACKENDS'),
    'normalize_world_model_backend': ('.WorldModelBackends', 'normalize_world_model_backend'),
    'create_world_model':           ('.WorldModelBackends', 'create_world_model'),
    'load_world_model':             ('.WorldModelBackends', 'load_world_model'),
    'list_world_model_backends':    ('.WorldModelBackends', 'list_world_model_backends'),
    'WorldModelPlannerConfig':      ('.WorldModelInference', 'WorldModelPlannerConfig'),
    'WorldModelActionEvaluation':  ('.WorldModelInference', 'WorldModelActionEvaluation'),
    'WorldModelPlan':               ('.WorldModelInference', 'WorldModelPlan'),
    'WorldModelRuntime':            ('.WorldModelInference', 'WorldModelRuntime'),
    'run_world_model_inference':    ('.WorldModelInference', 'run_world_model_inference'),
    'OccupancyGrid':                ('.SpatialPlanner', 'OccupancyGrid'),
    'SpatialPlannerConfig':         ('.SpatialPlanner', 'SpatialPlannerConfig'),
    'RouteCandidate':               ('.SpatialPlanner', 'RouteCandidate'),
    'GridPathPlanner':              ('.SpatialPlanner', 'GridPathPlanner'),
    'SpatialEntity':                ('.SpatialPerception', 'SpatialEntity'),
    'SpatialAnalysis':              ('.SpatialPerception', 'SpatialAnalysis'),
    'MapExtractionConfig':          ('.SpatialPerception', 'MapExtractionConfig'),
    'TopDownMapExtractor':          ('.SpatialPerception', 'TopDownMapExtractor'),
    'CallableSpatialAnalyzer':      ('.SpatialPerception', 'CallableSpatialAnalyzer'),
    'QwenVLSpatialAnalyzer':        ('.SpatialPerception', 'QwenVLSpatialAnalyzer'),
    'SpatialPlanResult':            ('.SpatialWorldModel', 'SpatialPlanResult'),
    'SpatialObservationEncoder':    ('.SpatialWorldModel', 'SpatialObservationEncoder'),
    'SpatialBeliefMap':             ('.SpatialWorldModel', 'SpatialBeliefMap'),
    'SpatialTensorObservationEncoder': ('.SpatialWorldModel', 'SpatialTensorObservationEncoder'),
    'WorldModelRouteScorer':        ('.SpatialWorldModel', 'WorldModelRouteScorer'),
    'SpatialWorldModelCoordinator': ('.SpatialWorldModel', 'SpatialWorldModelCoordinator'),
    'SpatialTrajectoryConfig':      ('.SpatialWorldModelData', 'SpatialTrajectoryConfig'),
    'SpatialTrajectoryBuilder':     ('.SpatialWorldModelData', 'SpatialTrajectoryBuilder'),
    'generate_spatial_world_model_dataset': ('.SpatialWorldModelData', 'generate_spatial_world_model_dataset'),
    'SpatialSequenceConfig':        ('.SpatialWorldModelData', 'SpatialSequenceConfig'),
    'SpatialSequenceTrajectoryBuilder': ('.SpatialWorldModelData', 'SpatialSequenceTrajectoryBuilder'),
    'generate_spatial_sequence_dataset': ('.SpatialWorldModelData', 'generate_spatial_sequence_dataset'),
    'SpatialCEMPlannerConfig':      ('.SpatialWorldModelControl', 'SpatialCEMPlannerConfig'),
    'SpatialCEMPlan':               ('.SpatialWorldModelControl', 'SpatialCEMPlan'),
    'SpatialClosedLoopResult':      ('.SpatialWorldModelControl', 'SpatialClosedLoopResult'),
    'SpatialClosedLoopPlanner':     ('.SpatialWorldModelControl', 'SpatialClosedLoopPlanner'),
    'evaluate_spatial_world_model': ('.SpatialWorldModelEvaluation', 'evaluate_spatial_world_model'),
    'save_spatial_plan_json':       ('.SpatialVisualization', 'save_spatial_plan_json'),
    'render_spatial_plan_html':     ('.SpatialVisualization', 'render_spatial_plan_html'),
    'render_spatial_plan_png':      ('.SpatialVisualization', 'render_spatial_plan_png'),
    'save_occupancy_mask_png':      ('.SpatialVisualization', 'save_occupancy_mask_png'),
    'SpatialPlanRequest':           ('.SpatialAPI', 'SpatialPlanRequest'),
    'SpatialStudioSettings':        ('.SpatialAPI', 'SpatialStudioSettings'),
    'SpatialStudioService':         ('.SpatialAPI', 'SpatialStudioService'),
    'create_spatial_studio_app':    ('.SpatialAPI', 'create_spatial_studio_app'),
    'WorldAgentError':              ('.WorldAgent', 'WorldAgentError'),
    'WorldAgentSettings':           ('.WorldAgent', 'WorldAgentSettings'),
    'WorldObservation':             ('.WorldAgent', 'WorldObservation'),
    'WorldState':                   ('.WorldAgent', 'WorldState'),
    'WorldPlan':                    ('.WorldAgent', 'WorldPlan'),
    'WorldSimulation':              ('.WorldAgent', 'WorldSimulation'),
    'WorldFeedback':                ('.WorldAgent', 'WorldFeedback'),
    'WorldAgentStore':              ('.WorldAgent', 'WorldAgentStore'),
    'WorldAgentRuntime':            ('.WorldAgent', 'WorldAgentRuntime'),
    'WorldAnalyzeRequest':          ('.WorldAgentAPI', 'WorldAnalyzeRequest'),
    'WorldPlanRequest':             ('.WorldAgentAPI', 'WorldPlanRequest'),
    'WorldSimulationRequest':       ('.WorldAgentAPI', 'WorldSimulationRequest'),
    'WorldFeedbackRequest':         ('.WorldAgentAPI', 'WorldFeedbackRequest'),
    'create_world_agent_app':       ('.WorldAgentAPI', 'create_world_agent_app'),
    'VisionBackboneConfig':         ('.VisionBackbones', 'VisionBackboneConfig'),
    'VisionBackboneRegistry':       ('.VisionBackbones', 'VisionBackboneRegistry'),
    'list_vision_backbones':        ('.VisionBackbones', 'list_vision_backbones'),
    'MultimodalProjectorConfig':    ('.MultimodalProjector', 'MultimodalProjectorConfig'),
    'MultimodalProjectorFactory':   ('.MultimodalProjector', 'MultimodalProjectorFactory'),
    'PostTrainingDataAdapter':      ('.PostTrainingData', 'PostTrainingDataAdapter'),
    'NormalizationReport':          ('.PostTrainingData', 'NormalizationReport'),
    'normalize_post_training_record': ('.PostTrainingData', 'normalize_post_training_record'),
    'normalize_post_training_file': ('.PostTrainingData', 'normalize_post_training_file'),
    'ModelExperimentPlanner':       ('.ModelExperimentPlanner', 'ModelExperimentPlanner'),
    'ModelExperimentConfig':        ('.ModelExperimentPlanner', 'ModelExperimentConfig'),
    'ModelExperimentBundle':        ('.ModelExperimentPlanner', 'ModelExperimentBundle'),
    'ModelExperimentRun':           ('.ModelExperimentPlanner', 'ModelExperimentRun'),
    'DomainModelBuilder':           ('.DomainBuilder', 'DomainModelBuilder'),
    'DomainBuildConfig':            ('.DomainBuilder', 'DomainBuildConfig'),
    'DomainRecipe':                 ('.DomainBuilder', 'DomainRecipe'),
    'list_domain_recipes':          ('.DomainBuilder', 'list_domain_recipes'),
    'DistributedConfig':            ('.DistributedConfig', 'DistributedConfig'),
    'TrainingOrchestrator':         ('.TrainingOrchestrator', 'TrainingOrchestrator'),
    'TrainingDataInspector':        ('.TrainingDataInspector', 'TrainingDataInspector'),
    'TrainingDataInspection':       ('.TrainingDataInspector', 'TrainingDataInspection'),
    'inspect_training_data':        ('.TrainingDataInspector', 'inspect_training_data'),
    'TrainingPlanEstimator':        ('.TrainingPlanEstimator', 'TrainingPlanEstimator'),
    'TrainingPlanEstimate':         ('.TrainingPlanEstimator', 'TrainingPlanEstimate'),
    'estimate_training_plan':       ('.TrainingPlanEstimator', 'estimate_training_plan'),
    'SimpleFlowCompiler':           ('.SimpleFlow', 'SimpleFlowCompiler'),
    'TrainingConfigValidator':      ('.TrainingConfigValidator', 'TrainingConfigValidator'),
    'TrainingConfigValidation':     ('.TrainingConfigValidator', 'TrainingConfigValidation'),
    'validate_training_config':     ('.TrainingConfigValidator', 'validate_training_config'),
    'EvaluationReleaseGate':        ('.ReleaseGate', 'EvaluationReleaseGate'),
    'ReleaseGateResult':            ('.ReleaseGate', 'ReleaseGateResult'),
    'evaluate_release_gate':        ('.ReleaseGate', 'evaluate_release_gate'),
    'ModelExportRequest':           ('.ModelExporter', 'ModelExportRequest'),
    'ModelExportResult':            ('.ModelExporter', 'ModelExportResult'),
    'ModelExporter':                ('.ModelExporter', 'ModelExporter'),
    'export_model':                 ('.ModelExporter', 'export_model'),
    'InferenceServerSettings':      ('.InferenceServer', 'InferenceServerSettings'),
    'LocalGenerationEngine':        ('.InferenceServer', 'LocalGenerationEngine'),
    'create_inference_app':         ('.InferenceServer', 'create_inference_app'),
    'load_inference_model':         ('.InferenceServer', 'load_inference_model'),
    'SmokeTestRunner':              ('.SmokeTestRunner', 'SmokeTestRunner'),
    'SmokeTestResult':              ('.SmokeTestRunner', 'SmokeTestResult'),
    'SmokeCommandResult':           ('.SmokeTestRunner', 'SmokeCommandResult'),
    'run_smoke_tests':              ('.SmokeTestRunner', 'run_smoke_tests'),
    'ExperimentTracker':            ('.ExperimentTracker', 'ExperimentTracker'),
    'BenchmarkRunner':              ('.BenchmarkRunner', 'BenchmarkRunner'),
    'ScalingLawAnalyzer':           ('.ScalingLawAnalyzer', 'ScalingLawAnalyzer'),
    'PretrainRunPlan':              ('.ScalingLawAnalyzer', 'PretrainRunPlan'),
    'CurriculumScheduler':          ('.CurriculumScheduler', 'CurriculumScheduler'),
    # 新增 v2.3.0
    'TrainingMonitor':              ('.TrainingMonitor', 'TrainingMonitor'),
    'DataMixer':                    ('.DataPipeline', 'DataMixer'),
    'GRPOConfig':                   ('.GRPOTrainer', 'GRPOConfig'),
    'GRPOTrainer':                  ('.GRPOTrainer', 'GRPOTrainer'),
    'RLScalingTrainer':             ('.RLScaling', 'RLScalingTrainer'),
    'RLScalingConfig':              ('.RLScaling', 'RLScalingConfig'),
    'RolloutBuffer':                ('.RLScaling', 'RolloutBuffer'),
    'RolloutSample':                ('.RLScaling', 'RolloutSample'),
    'RolloutSegment':               ('.RLScaling', 'RolloutSegment'),
    'RewardManager':                ('.RLScaling', 'RewardManager'),
    'TriageConfig':                 ('.RLScaling', 'TriageConfig'),
    'ActionRoleClassifier':         ('.RLScaling', 'ActionRoleClassifier'),
    'TriageCreditAssigner':         ('.RLScaling', 'TriageCreditAssigner'),
    'TriageRolloutProcessor':       ('.RLScaling', 'TriageRolloutProcessor'),
    'TrainingStrategyAdvisor':      ('.TrainingStrategyAdvisor', 'TrainingStrategyAdvisor'),
    'FeasibilityReport':            ('.TrainingStrategyAdvisor', 'FeasibilityReport'),
    'TrainingRoute':                ('.TrainingStrategyAdvisor', 'TrainingRoute'),
    'BudgetProfile':                ('.TrainingStrategyAdvisor', 'BudgetProfile'),
    'PretrainStabilityCallback':    ('.PretrainStability', 'PretrainStabilityCallback'),
    'StabilityConfig':              ('.PretrainStability', 'StabilityConfig'),
    'StabilityEvent':               ('.PretrainStability', 'StabilityEvent'),
    'CheckpointInspector':          ('.PretrainStability', 'CheckpointInspector'),
    'DensePretrainer':              ('.DensePretrainer', 'DensePretrainer'),
    'init_weights_llama_style':     ('.DensePretrainer', 'init_weights_llama_style'),
    'init_weights_deepseek_style':  ('.DensePretrainer', 'init_weights_deepseek_style'),
    # v2.4.0
    'ConstitutionalAI':             ('.FrontierAlign', 'ConstitutionalAI'),
    'ProcessRewardModel':           ('.FrontierAlign', 'ProcessRewardModel'),
    'RejectionSampling':            ('.FrontierAlign', 'RejectionSampling'),
    'FrontierAlignmentPipeline':    ('.FrontierAlign', 'FrontierAlignmentPipeline'),
    # v2.5.0
    'EMA':                          ('.AdvancedTechniques', 'EMA'),
    'EMACallback':                  ('.AdvancedTechniques', 'EMACallback'),
    'SelfConsistency':              ('.AdvancedTechniques', 'SelfConsistency'),
    'EvolInstruct':                 ('.AdvancedTechniques', 'EvolInstruct'),
    'ModelSoup':                    ('.AdvancedTechniques', 'ModelSoup'),
    'InstructionBacktranslation':   ('.AdvancedTechniques', 'InstructionBacktranslation'),
    # v2.6.0
    'MultiTokenPredictionHead':     ('.ExclusiveTechniques', 'MultiTokenPredictionHead'),
    'MultiTokenPredictionLoss':     ('.ExclusiveTechniques', 'MultiTokenPredictionLoss'),
    'add_mtp_to_model':             ('.ExclusiveTechniques', 'add_mtp_to_model'),
    'AuxLossFreeRouter':            ('.ExclusiveTechniques', 'AuxLossFreeRouter'),
    'AuxLossFreeMoELayer':          ('.ExclusiveTechniques', 'AuxLossFreeMoELayer'),
    'IterativeAlignment':           ('.ExclusiveTechniques', 'IterativeAlignment'),
    'TestTimeCompute':              ('.ExclusiveTechniques', 'TestTimeCompute'),
    'RLAIF':                        ('.ExclusiveTechniques', 'RLAIF'),
    'SLURPMixer':                   ('.ExclusiveTechniques', 'SLURPMixer'),
    'RoPEScaling':                  ('.ExclusiveTechniques', 'RoPEScaling'),
    'SparseAutoencoder':            ('.ExclusiveTechniques', 'SparseAutoencoder'),
    # v2.7.0
    'TeacherInterface':             ('.UniversalDistiller', 'TeacherInterface'),
    'DataDistiller':                ('.UniversalDistiller', 'DataDistiller'),
    'MultiTeacherDistiller':        ('.UniversalDistiller', 'MultiTeacherDistiller'),
    'CapabilityDistiller':          ('.UniversalDistiller', 'CapabilityDistiller'),
    'AutoDistiller':                ('.UniversalDistiller', 'AutoDistiller'),
    'DistillConfig':                ('.UniversalDistiller', 'DistillConfig'),
    'OnPolicyTeacherSpec':          ('.OnPolicyDistillation', 'OnPolicyTeacherSpec'),
    'TeacherPolicySignal':          ('.OnPolicyDistillation', 'TeacherPolicySignal'),
    'MOPDConfig':                   ('.OnPolicyDistillation', 'MOPDConfig'),
    'MultiTeacherOnPolicyDistiller': ('.OnPolicyDistillation', 'MultiTeacherOnPolicyDistiller'),
    # 数据目录 + 质量分类器
    'DataCatalog':                  ('.DataCatalog', 'DataCatalog'),
    'DataQualityClassifier':        ('.DataCatalog', 'DataQualityClassifier'),
    # Chat UI + 部署
    'ChatUI':                       ('.ChatUI', 'ChatUI'),
    'Deploy':                       ('.Deploy', 'Deploy'),
    # 轻量化 + 快速蒸馏
    'Lightweight':                  ('.Lightweight', 'Lightweight'),
    'RapidDistill':                 ('.RapidDistill', 'RapidDistill'),
    'SmartRouter':                  ('.RapidDistill', 'SmartRouter'),
    'ParallelAPICaller':            ('.RapidDistill', 'ParallelAPICaller'),
    'TEACHER_PROFILES':             ('.RapidDistill', 'TEACHER_PROFILES'),
    'DOWNLOADABLE_TEACHERS':        ('.RapidDistill', 'DOWNLOADABLE_TEACHERS'),
    'ModelDownloader':              ('.RapidDistill', 'ModelDownloader'),
    'LocalTeacherPool':             ('.RapidDistill', 'LocalTeacherPool'),
    'quick_local_distill':          ('.RapidDistill', 'quick_local_distill'),
    # 安全生成
    'SafeGenerate':                 ('.SafeGenerate', 'SafeGenerate'),
    'AntiRepeatGenerator':          ('.SafeGenerate', 'AntiRepeatGenerator'),
    'OutputSafetyFilter':           ('.SafeGenerate', 'OutputSafetyFilter'),
    'filter_toxic_texts':           ('.SafeGenerate', 'filter_toxic_texts'),
    # 训练工具
    'check_environment':            ('.TrainerUtils', 'check_environment'),
    'TrainingDiagnostics':          ('.TrainerUtils', 'TrainingDiagnostics'),
    'TrainingReportCard':           ('.TrainerUtils', 'TrainingReportCard'),
    'EarlyStopping':                ('.TrainerUtils', 'EarlyStopping'),
    'auto_train_best_small_model':  ('.TrainerUtils', 'auto_train_best_small_model'),
}


def __getattr__(name):
    if name in _LAZY_IMPORT_MAP:
        mod_path, attr = _LAZY_IMPORT_MAP[name]
        module = importlib.import_module(mod_path, package=__package__)
        value = getattr(module, attr)
        globals()[name] = value
        return value
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")


def __dir__():
    return sorted(set(globals()) | set(__all__) | set(_LAZY_IMPORT_MAP))
