"""Lazy import targets for the public :mod:`saddlellm` API.

This module contains data only. Keeping the registry separate leaves package
initialization small and makes additions to the public surface easy to review.
"""

LAZY_IMPORTS: dict[str, tuple[str, str | None]] = {
    # Core training APIs
    "LoRATuner": (".tuning.LoRATuner", "LoRATuner"),
    "train_sft": (".training.PeftSFTTrainer", "train_model"),
    "train_full": (".tuning.TRLFullFineTuner", "train_model"),
    "PreferenceTrainer": (".training.Preference", "PreferenceTrainer"),
    "PreferenceTrainConfig": (".training.Preference", "PreferenceTrainConfig"),
    "train_preference": (".training.Preference", "train_preference"),
    "quantize_model": (".compression.quantizer", "ModelQuantizer"),
    "prune_model": (".compression.pruner", "ModelPruner"),
    "distill_model": (".distillation.DistillationTrainer", "DistillationTrainer"),
    "run_large_model_operator": (".agents.RealWorldOperators", "run_large_model_operator"),
    "run_agent_operator": (".agents.AgentOperators", "run_agent_operator"),
    "normalize_agent_config": (".agents.AgentOperators", "normalize_agent_config"),
    "balance_data": (".data.DataBalance", "BalancedPretrainer"),
    "evaluate_llm": (".evaluation.LLModelEvalute", "Evaluator"),
    "Evaluator": (".evaluation.LLModelEvalute", "Evaluator"),
    "process_text": (".data.text_processing", "TextCleaner"),
    "unsloth_load_lora_model": (".models.load_model", "unsloth_load_lora_model"),
    "transfomer_load_lora": (".models.load_model", "transfomer_load_lora"),
    "src_mode_transformer_load": (".models.load_model", "src_mode_transformer_load"),
    # Model, data, multimodal, world-model, and lifecycle APIs
    "TokenizerTrainer": (".models.TokenizerTrainer", "TokenizerTrainer"),
    "TokenizerEvalResult": (".models.TokenizerTrainer", "TokenizerEvalResult"),
    "ModelRegistry": (".models.ModelRegistry", "ModelRegistry"),
    "ArchitectureRegistry": (".models.Architecture", "ArchitectureRegistry"),
    "ArchitectureSupport": (".models.Architecture", "ArchitectureSupport"),
    "DataPipeline": (".data.pipeline", "DataPipeline"),
    "DataMixPlanner": (".data.DataStrategy", "DataMixPlanner"),
    "DataMixPlan": (".data.DataStrategy", "DataMixPlan"),
    "DataBucketPlan": (".data.DataStrategy", "DataBucketPlan"),
    "ContaminationDetector": (".data.DataStrategy", "ContaminationDetector"),
    "ContaminationReport": (".data.DataStrategy", "ContaminationReport"),
    "PretrainEvalSuite": (".evaluation.PretrainEvalSuite", "PretrainEvalSuite"),
    "EvalTaskSpec": (".evaluation.PretrainEvalSuite", "EvalTaskSpec"),
    "EvalSuiteResult": (".evaluation.PretrainEvalSuite", "EvalSuiteResult"),
    "PretrainReport": (".experiments.PretrainReport", "PretrainReport"),
    "PretrainReportResult": (".experiments.PretrainReport", "PretrainReportResult"),
    "ReportFinding": (".experiments.PretrainReport", "ReportFinding"),
    "PretrainExperimentRunner": (
        ".experiments.PretrainExperimentRunner",
        "PretrainExperimentRunner",
    ),
    "PretrainExperimentConfig": (
        ".experiments.PretrainExperimentRunner",
        "PretrainExperimentConfig",
    ),
    "ExperimentBundle": (".experiments.PretrainExperimentRunner", "ExperimentBundle"),
    "ExperimentRunManifest": (".experiments.PretrainExperimentRunner", "ExperimentRunManifest"),
    "LLMTrainingFactory": (".factory.TrainingFactory", "LLMTrainingFactory"),
    "FactoryConfig": (".factory.TrainingFactory", "FactoryConfig"),
    "FactoryStatus": (".factory.TrainingFactory", "FactoryStatus"),
    "DatasetManifest": (".data.DatasetManifest", "DatasetManifest"),
    "DatasetManifestEntry": (".data.DatasetManifest", "DatasetManifestEntry"),
    "FactoryBackendPlanner": (".factory.FactoryBackendPlanner", "FactoryBackendPlanner"),
    "ParallelismPlan": (".factory.FactoryBackendPlanner", "ParallelismPlan"),
    "TrainingBackendSpec": (".factory.FactoryBackendPlanner", "TrainingBackendSpec"),
    "BackendAdapterRegistry": (".factory.BackendAdapters", "BackendAdapterRegistry"),
    "LaunchPlan": (".factory.BackendAdapters", "LaunchPlan"),
    "DistributedRuntimeInfo": (".training.DistributedRuntime", "DistributedRuntimeInfo"),
    "current_distributed_runtime": (
        ".training.DistributedRuntime",
        "current_distributed_runtime",
    ),
    "validate_distributed_runtime": (
        ".training.DistributedRuntime",
        "validate_distributed_runtime",
    ),
    "distributed_barrier": (".training.DistributedRuntime", "distributed_barrier"),
    "ModelBlueprint": (".models.ModelBlueprint", "ModelBlueprint"),
    "ModelBlueprintLab": (".models.ModelBlueprint", "ModelBlueprintLab"),
    "AttentionBlueprint": (".models.ModelBlueprint", "AttentionBlueprint"),
    "FFNBlueprint": (".models.ModelBlueprint", "FFNBlueprint"),
    "ResidualBlueprint": (".models.ModelBlueprint", "ResidualBlueprint"),
    "LayerBlueprint": (".models.ModelBlueprint", "LayerBlueprint"),
    "ObjectiveBlueprint": (".models.ModelBlueprint", "ObjectiveBlueprint"),
    "VisionBlueprint": (".models.ModelBlueprint", "VisionBlueprint"),
    "ProjectorBlueprint": (".models.ModelBlueprint", "ProjectorBlueprint"),
    "ModelComponentRegistry": (".models.ModelBuilder", "ModelComponentRegistry"),
    "SaddleModelBuilder": (".models.ModelBuilder", "SaddleModelBuilder"),
    "SaddleModelConfig": (".models.SaddleModeling", "SaddleModelConfig"),
    "SaddleForCausalLM": (".models.SaddleModeling", "SaddleForCausalLM"),
    "SaddleDecoderLayer": (".models.SaddleModeling", "SaddleDecoderLayer"),
    "SaddleAttention": (".models.SaddleModeling", "SaddleAttention"),
    "SaddleSwiGLU": (".models.SaddleModeling", "SaddleSwiGLU"),
    "SaddleMoE": (".models.SaddleModeling", "SaddleMoE"),
    "SaddleRMSNorm": (".models.SaddleModeling", "SaddleRMSNorm"),
    "SaddleCausalLMOutput": (".models.SaddleModeling", "SaddleCausalLMOutput"),
    "SaddleGenerationOutput": (".models.SaddleModeling", "SaddleGenerationOutput"),
    "is_saddle_checkpoint": (".models.ModelLoader", "is_saddle_checkpoint"),
    "load_causal_lm": (".models.ModelLoader", "load_causal_lm"),
    "load_model_and_tokenizer": (".models.ModelLoader", "load_model_and_tokenizer"),
    "SaddleTrainer": (".training.NativeTrainer", "SaddleTrainer"),
    "ModelBackendCapabilities": (".models.ModelAdapter", "ModelBackendCapabilities"),
    "ModelAdapter": (".models.ModelAdapter", "ModelAdapter"),
    "SaddleModelAdapter": (".models.ModelAdapter", "SaddleModelAdapter"),
    "HuggingFaceModelAdapter": (".models.ModelAdapter", "HuggingFaceModelAdapter"),
    "get_model_adapter": (".models.ModelAdapter", "get_model_adapter"),
    "NativeSFTConfig": (".training.NativePostTraining", "NativeSFTConfig"),
    "NativeDPOConfig": (".training.NativePostTraining", "NativeDPOConfig"),
    "train_native_sft": (".training.NativePostTraining", "train_native_sft"),
    "train_native_dpo": (".training.NativePostTraining", "train_native_dpo"),
    "ModelMetricsExtractor": (".models.ModelMetrics", "ModelMetricsExtractor"),
    "ModelMetricsCallback": (".models.ModelMetrics", "ModelMetricsCallback"),
    "ModelMetricSnapshot": (".models.ModelMetrics", "ModelMetricSnapshot"),
    "AttentionBackendRegistry": (".models.OperatorBackends", "AttentionBackendRegistry"),
    "AttentionBackendSpec": (".models.OperatorBackends", "AttentionBackendSpec"),
    "list_attention_backends": (".models.OperatorBackends", "list_attention_backends"),
    "MultimodalConfig": (".multimodal.MultimodalModeling", "MultimodalConfig"),
    "MultimodalForCausalLM": (".multimodal.MultimodalModeling", "MultimodalForCausalLM"),
    "MultimodalDataAdapter": (".multimodal.MultimodalData", "MultimodalDataAdapter"),
    "MultimodalSample": (".multimodal.MultimodalData", "MultimodalSample"),
    "MultimodalAsset": (".multimodal.MultimodalData", "MultimodalAsset"),
    "MultimodalSegment": (".multimodal.MultimodalData", "MultimodalSegment"),
    "normalize_multimodal_file": (".multimodal.MultimodalData", "normalize_multimodal_file"),
    "ModalityCodecSpec": (".multimodal.ModalityCodec", "ModalityCodecSpec"),
    "ModalityCodec": (".multimodal.ModalityCodec", "ModalityCodec"),
    "CallableModalityCodec": (".multimodal.ModalityCodec", "CallableModalityCodec"),
    "ModalityCodecRegistry": (".multimodal.ModalityCodec", "ModalityCodecRegistry"),
    "TextConditionEncoder": (".multimodal.BuiltinMediaCodecs", "TextConditionEncoder"),
    "HashTextConditionEncoder": (".multimodal.BuiltinMediaCodecs", "HashTextConditionEncoder"),
    "HuggingFaceTextConditionEncoder": (
        ".multimodal.BuiltinMediaCodecs",
        "HuggingFaceTextConditionEncoder",
    ),
    "build_text_condition_encoder": (
        ".multimodal.BuiltinMediaCodecs",
        "build_text_condition_encoder",
    ),
    "RGBImageCodec": (".multimodal.BuiltinMediaCodecs", "RGBImageCodec"),
    "WAVResidualCodec": (".multimodal.BuiltinMediaCodecs", "WAVResidualCodec"),
    "FrameVideoCodec": (".multimodal.BuiltinMediaCodecs", "FrameVideoCodec"),
    "register_builtin_media_codecs": (
        ".multimodal.BuiltinMediaCodecs",
        "register_builtin_media_codecs",
    ),
    "MediaCacheBuildConfig": (".multimodal.MediaCache", "MediaCacheBuildConfig"),
    "ShardedNpzStore": (".multimodal.MediaCache", "ShardedNpzStore"),
    "build_media_cache": (".multimodal.MediaCache", "build_media_cache"),
    "LatentFlowConfig": (".multimodal.LatentFlowModel", "LatentFlowConfig"),
    "ConditionalLatentFlowTransformer": (
        ".multimodal.LatentFlowModel",
        "ConditionalLatentFlowTransformer",
    ),
    "LatentFlowTrainingConfig": (".multimodal.LatentFlowTrainer", "LatentFlowTrainingConfig"),
    "CachedLatentDataset": (".multimodal.LatentFlowTrainer", "CachedLatentDataset"),
    "train_latent_flow": (".multimodal.LatentFlowTrainer", "train_latent_flow"),
    "save_latent_flow_checkpoint": (
        ".multimodal.LatentFlowTrainer",
        "save_latent_flow_checkpoint",
    ),
    "load_latent_flow_checkpoint": (
        ".multimodal.LatentFlowTrainer",
        "load_latent_flow_checkpoint",
    ),
    "MusicCodeConfig": (".multimodal.MusicCodeModel", "MusicCodeConfig"),
    "ConditionalMusicCodeTransformer": (
        ".multimodal.MusicCodeModel",
        "ConditionalMusicCodeTransformer",
    ),
    "MusicCodeTrainingConfig": (".multimodal.MusicCodeTrainer", "MusicCodeTrainingConfig"),
    "CachedMusicCodeDataset": (".multimodal.MusicCodeTrainer", "CachedMusicCodeDataset"),
    "train_music_code": (".multimodal.MusicCodeTrainer", "train_music_code"),
    "save_music_code_checkpoint": (".multimodal.MusicCodeTrainer", "save_music_code_checkpoint"),
    "load_music_code_checkpoint": (".multimodal.MusicCodeTrainer", "load_music_code_checkpoint"),
    "VideoLatentFlowConfig": (".multimodal.VideoLatentFlowModel", "VideoLatentFlowConfig"),
    "ConditionalVideoLatentFlowTransformer": (
        ".multimodal.VideoLatentFlowModel",
        "ConditionalVideoLatentFlowTransformer",
    ),
    "VideoLatentFlowTrainingConfig": (
        ".multimodal.VideoLatentFlowTrainer",
        "VideoLatentFlowTrainingConfig",
    ),
    "CachedVideoLatentDataset": (".multimodal.VideoLatentFlowTrainer", "CachedVideoLatentDataset"),
    "train_video_latent_flow": (".multimodal.VideoLatentFlowTrainer", "train_video_latent_flow"),
    "save_video_latent_flow_checkpoint": (
        ".multimodal.VideoLatentFlowTrainer",
        "save_video_latent_flow_checkpoint",
    ),
    "load_video_latent_flow_checkpoint": (
        ".multimodal.VideoLatentFlowTrainer",
        "load_video_latent_flow_checkpoint",
    ),
    "VLAActionSpace": (".multimodal.VLA", "VLAActionSpace"),
    "VLAAction": (".multimodal.VLA", "VLAAction"),
    "VLASample": (".multimodal.VLA", "VLASample"),
    "VLANormalizationReport": (".multimodal.VLA", "VLANormalizationReport"),
    "VLACollatorConfig": (".multimodal.VLA", "VLACollatorConfig"),
    "VLAActionTokenizer": (".multimodal.VLA", "VLAActionTokenizer"),
    "VLADataAdapter": (".multimodal.VLA", "VLADataAdapter"),
    "VLADataset": (".multimodal.VLA", "VLADataset"),
    "VLADataCollator": (".multimodal.VLA", "VLADataCollator"),
    "VLATrainingPlanner": (".multimodal.VLA", "VLATrainingPlanner"),
    "normalize_vla_file": (".multimodal.VLA", "normalize_vla_file"),
    "register_vla_action_tokens": (".multimodal.VLA", "register_vla_action_tokens"),
    "VLADataInspector": (".multimodal.VLADataInspector", "VLADataInspector"),
    "VLADataInspection": (".multimodal.VLADataInspector", "VLADataInspection"),
    "inspect_vla_data": (".multimodal.VLADataInspector", "inspect_vla_data"),
    "VLASFTConfig": (".multimodal.VLATrainer", "VLASFTConfig"),
    "train_vla_sft": (".multimodal.VLATrainer", "train_vla_sft"),
    "WorldModelConfig": (".world_models._WorldModel", "WorldModelConfig"),
    "RSSMState": (".world_models._WorldModel", "RSSMState"),
    "WorldModelOutput": (".world_models._WorldModel", "WorldModelOutput"),
    "WorldModelImagination": (".world_models._WorldModel", "WorldModelImagination"),
    "ObservationEncoder": (".world_models._WorldModel", "ObservationEncoder"),
    "ObservationDecoder": (".world_models._WorldModel", "ObservationDecoder"),
    "RSSMCell": (".world_models._WorldModel", "RSSMCell"),
    "WorldModel": (".world_models._WorldModel", "WorldModel"),
    "WorldModelDataError": (".world_models.WorldModelData", "WorldModelDataError"),
    "WorldModelTrajectoryDataset": (".world_models.WorldModelData", "WorldModelTrajectoryDataset"),
    "load_world_model_trajectories": (
        ".world_models.WorldModelData",
        "load_world_model_trajectories",
    ),
    "split_world_model_trajectories": (
        ".world_models.WorldModelData",
        "split_world_model_trajectories",
    ),
    "infer_world_model_dimensions": (".world_models.WorldModelData", "infer_world_model_dimensions"),
    "WorldModelDataConfig": (".world_models._WorldModelTrainer", "WorldModelDataConfig"),
    "WorldModelTrainingConfig": (".world_models._WorldModelTrainer", "WorldModelTrainingConfig"),
    "WorldModelTrainer": (".world_models._WorldModelTrainer", "WorldModelTrainer"),
    "prepare_world_model_training": (
        ".world_models._WorldModelTrainer",
        "prepare_world_model_training",
    ),
    "train_world_model_from_config": (
        ".world_models._WorldModelTrainer",
        "train_world_model_from_config",
    ),
    "train_world_model": (".world_models._WorldModelTrainer", "train_world_model"),
    "CategoricalWorldModelConfig": (
        ".world_models._CategoricalWorldModel",
        "CategoricalWorldModelConfig",
    ),
    "CategoricalWorldModelOutput": (
        ".world_models._CategoricalWorldModel",
        "CategoricalWorldModelOutput",
    ),
    "CategoricalRSSMCell": (".world_models._CategoricalWorldModel", "CategoricalRSSMCell"),
    "CategoricalWorldModel": (".world_models._CategoricalWorldModel", "CategoricalWorldModel"),
    "symlog": (".world_models._CategoricalWorldModel", "symlog"),
    "symexp": (".world_models._CategoricalWorldModel", "symexp"),
    "NATIVE_WORLD_MODEL_BACKENDS": (
        ".world_models.WorldModelBackends",
        "NATIVE_WORLD_MODEL_BACKENDS",
    ),
    "normalize_world_model_backend": (
        ".world_models.WorldModelBackends",
        "normalize_world_model_backend",
    ),
    "create_world_model": (".world_models.WorldModelBackends", "create_world_model"),
    "load_world_model": (".world_models.WorldModelBackends", "load_world_model"),
    "list_world_model_backends": (".world_models.WorldModelBackends", "list_world_model_backends"),
    "WorldModelPlannerConfig": (".world_models.WorldModelInference", "WorldModelPlannerConfig"),
    "WorldModelActionEvaluation": (
        ".world_models.WorldModelInference",
        "WorldModelActionEvaluation",
    ),
    "WorldModelPlan": (".world_models.WorldModelInference", "WorldModelPlan"),
    "WorldModelRuntime": (".world_models.WorldModelInference", "WorldModelRuntime"),
    "run_world_model_inference": (".world_models.WorldModelInference", "run_world_model_inference"),
    "EYE_ACTION_SIZE": (".spatial.prosthetic_eye_control", "EYE_ACTION_SIZE"),
    "EYE_CONTROL_SCHEMA_VERSION": (
        ".spatial.prosthetic_eye_control",
        "EYE_CONTROL_SCHEMA_VERSION",
    ),
    "EYE_OBSERVATION_FIELDS": (".spatial.prosthetic_eye_control", "EYE_OBSERVATION_FIELDS"),
    "EYE_OBSERVATION_SIZE": (".spatial.prosthetic_eye_control", "EYE_OBSERVATION_SIZE"),
    "EyeControlCommand": (".spatial.prosthetic_eye_control", "EyeControlCommand"),
    "EyeControlError": (".spatial.prosthetic_eye_control", "EyeControlError"),
    "EyeControlLoop": (".spatial.prosthetic_eye_control", "EyeControlLoop"),
    "EyeHardwareAdapter": (".spatial.prosthetic_eye_control", "EyeHardwareAdapter"),
    "EyeObservation": (".spatial.prosthetic_eye_control", "EyeObservation"),
    "EyePIDConfig": (".spatial.prosthetic_eye_control", "EyePIDConfig"),
    "EyePIDController": (".spatial.prosthetic_eye_control", "EyePIDController"),
    "EyePlantConfig": (".spatial.prosthetic_eye_control", "EyePlantConfig"),
    "EyeSafetyConfig": (".spatial.prosthetic_eye_control", "EyeSafetyConfig"),
    "EyeSafetyEnvelope": (".spatial.prosthetic_eye_control", "EyeSafetyEnvelope"),
    "EyeSafetyResult": (".spatial.prosthetic_eye_control", "EyeSafetyResult"),
    "EyeTarget": (".spatial.prosthetic_eye_control", "EyeTarget"),
    "ProstheticEyeController": (".spatial.prosthetic_eye_control", "ProstheticEyeController"),
    "ProstheticEyeSimulator": (".spatial.prosthetic_eye_control", "ProstheticEyeSimulator"),
    "generate_prosthetic_eye_dataset": (
        ".spatial.prosthetic_eye_control",
        "generate_prosthetic_eye_dataset",
    ),
    "simulate_prosthetic_eye_control": (
        ".spatial.prosthetic_eye_control",
        "simulate_prosthetic_eye_control",
    ),
    "OccupancyGrid": (".spatial.SpatialPlanner", "OccupancyGrid"),
    "SpatialPlannerConfig": (".spatial.SpatialPlanner", "SpatialPlannerConfig"),
    "RouteCandidate": (".spatial.SpatialPlanner", "RouteCandidate"),
    "GridPathPlanner": (".spatial.SpatialPlanner", "GridPathPlanner"),
    "SpatialEntity": (".spatial.SpatialPerception", "SpatialEntity"),
    "SpatialAnalysis": (".spatial.SpatialPerception", "SpatialAnalysis"),
    "MapExtractionConfig": (".spatial.SpatialPerception", "MapExtractionConfig"),
    "TopDownMapExtractor": (".spatial.SpatialPerception", "TopDownMapExtractor"),
    "CallableSpatialAnalyzer": (".spatial.SpatialPerception", "CallableSpatialAnalyzer"),
    "QwenVLSpatialAnalyzer": (".spatial.SpatialPerception", "QwenVLSpatialAnalyzer"),
    "SpatialPlanResult": (".spatial.SpatialWorldModel", "SpatialPlanResult"),
    "SpatialObservationEncoder": (".spatial.SpatialWorldModel", "SpatialObservationEncoder"),
    "SpatialBeliefMap": (".spatial.SpatialWorldModel", "SpatialBeliefMap"),
    "SpatialTensorObservationEncoder": (
        ".spatial.SpatialWorldModel",
        "SpatialTensorObservationEncoder",
    ),
    "WorldModelRouteScorer": (".spatial.SpatialWorldModel", "WorldModelRouteScorer"),
    "SpatialWorldModelCoordinator": (
        ".spatial.SpatialWorldModel",
        "SpatialWorldModelCoordinator",
    ),
    "SpatialTrajectoryConfig": (".spatial.SpatialWorldModelData", "SpatialTrajectoryConfig"),
    "SpatialTrajectoryBuilder": (".spatial.SpatialWorldModelData", "SpatialTrajectoryBuilder"),
    "generate_spatial_world_model_dataset": (
        ".spatial.SpatialWorldModelData",
        "generate_spatial_world_model_dataset",
    ),
    "SpatialSequenceConfig": (".spatial.SpatialWorldModelData", "SpatialSequenceConfig"),
    "SpatialSequenceTrajectoryBuilder": (
        ".spatial.SpatialWorldModelData",
        "SpatialSequenceTrajectoryBuilder",
    ),
    "generate_spatial_sequence_dataset": (
        ".spatial.SpatialWorldModelData",
        "generate_spatial_sequence_dataset",
    ),
    "SpatialCEMPlannerConfig": (".spatial.SpatialWorldModelControl", "SpatialCEMPlannerConfig"),
    "SpatialCEMPlan": (".spatial.SpatialWorldModelControl", "SpatialCEMPlan"),
    "SpatialClosedLoopResult": (".spatial.SpatialWorldModelControl", "SpatialClosedLoopResult"),
    "SpatialClosedLoopPlanner": (
        ".spatial.SpatialWorldModelControl",
        "SpatialClosedLoopPlanner",
    ),
    "evaluate_spatial_world_model": (
        ".spatial.SpatialWorldModelEvaluation",
        "evaluate_spatial_world_model",
    ),
    "save_spatial_plan_json": (".spatial.SpatialVisualization", "save_spatial_plan_json"),
    "render_spatial_plan_html": (".spatial.SpatialVisualization", "render_spatial_plan_html"),
    "render_spatial_plan_png": (".spatial.SpatialVisualization", "render_spatial_plan_png"),
    "save_occupancy_mask_png": (".spatial.SpatialVisualization", "save_occupancy_mask_png"),
    "SpatialPlanRequest": (".spatial.SpatialAPI", "SpatialPlanRequest"),
    "SpatialStudioSettings": (".spatial.SpatialAPI", "SpatialStudioSettings"),
    "SpatialStudioService": (".spatial.SpatialAPI", "SpatialStudioService"),
    "create_spatial_studio_app": (".spatial.SpatialAPI", "create_spatial_studio_app"),
    "WorldAgentError": (".spatial.WorldAgent", "WorldAgentError"),
    "WorldAgentSettings": (".spatial.WorldAgent", "WorldAgentSettings"),
    "WorldObservation": (".spatial.WorldAgent", "WorldObservation"),
    "WorldState": (".spatial.WorldAgent", "WorldState"),
    "WorldPlan": (".spatial.WorldAgent", "WorldPlan"),
    "WorldSimulation": (".spatial.WorldAgent", "WorldSimulation"),
    "WorldFeedback": (".spatial.WorldAgent", "WorldFeedback"),
    "WorldAgentStore": (".spatial.WorldAgent", "WorldAgentStore"),
    "WorldAgentRuntime": (".spatial.WorldAgent", "WorldAgentRuntime"),
    "WorldAnalyzeRequest": (".spatial.WorldAgentAPI", "WorldAnalyzeRequest"),
    "WorldPlanRequest": (".spatial.WorldAgentAPI", "WorldPlanRequest"),
    "WorldSimulationRequest": (".spatial.WorldAgentAPI", "WorldSimulationRequest"),
    "WorldFeedbackRequest": (".spatial.WorldAgentAPI", "WorldFeedbackRequest"),
    "create_world_agent_app": (".spatial.WorldAgentAPI", "create_world_agent_app"),
    "VisionBackboneConfig": (".multimodal.VisionBackbones", "VisionBackboneConfig"),
    "VisionBackboneRegistry": (".multimodal.VisionBackbones", "VisionBackboneRegistry"),
    "list_vision_backbones": (".multimodal.VisionBackbones", "list_vision_backbones"),
    "MultimodalProjectorConfig": (".multimodal.MultimodalProjector", "MultimodalProjectorConfig"),
    "MultimodalProjectorFactory": (
        ".multimodal.MultimodalProjector",
        "MultimodalProjectorFactory",
    ),
    "PostTrainingDataAdapter": (".data.PostTrainingData", "PostTrainingDataAdapter"),
    "NormalizationReport": (".data.PostTrainingData", "NormalizationReport"),
    "normalize_post_training_record": (
        ".data.PostTrainingData",
        "normalize_post_training_record",
    ),
    "normalize_post_training_file": (
        ".data.PostTrainingData",
        "normalize_post_training_file",
    ),
    "ModelExperimentPlanner": (".experiments.ModelExperimentPlanner", "ModelExperimentPlanner"),
    "ModelExperimentConfig": (".experiments.ModelExperimentPlanner", "ModelExperimentConfig"),
    "ModelExperimentBundle": (".experiments.ModelExperimentPlanner", "ModelExperimentBundle"),
    "ModelExperimentRun": (".experiments.ModelExperimentPlanner", "ModelExperimentRun"),
    "DomainModelBuilder": (".factory.DomainBuilder", "DomainModelBuilder"),
    "DomainBuildConfig": (".factory.DomainBuilder", "DomainBuildConfig"),
    "DomainRecipe": (".factory.DomainBuilder", "DomainRecipe"),
    "list_domain_recipes": (".factory.DomainBuilder", "list_domain_recipes"),
    "DistributedConfig": (".training.DistributedConfig", "DistributedConfig"),
    "TrainingOrchestrator": (".training.TrainingOrchestrator", "TrainingOrchestrator"),
    "TrainingDataInspector": (".data.TrainingDataInspector", "TrainingDataInspector"),
    "TrainingDataInspection": (".data.TrainingDataInspector", "TrainingDataInspection"),
    "inspect_training_data": (".data.TrainingDataInspector", "inspect_training_data"),
    "TrainingPlanEstimator": (".training.TrainingPlanEstimator", "TrainingPlanEstimator"),
    "TrainingPlanEstimate": (".training.TrainingPlanEstimator", "TrainingPlanEstimate"),
    "estimate_training_plan": (".training.TrainingPlanEstimator", "estimate_training_plan"),
    "QuickstartResult": (".factory.Quickstart", "QuickstartResult"),
    "create_quickstart": (".factory.Quickstart", "create_quickstart"),
    "TrainingConfigValidator": (".training.TrainingConfigValidator", "TrainingConfigValidator"),
    "TrainingConfigValidation": (
        ".training.TrainingConfigValidator",
        "TrainingConfigValidation",
    ),
    "validate_training_config": (
        ".training.TrainingConfigValidator",
        "validate_training_config",
    ),
    "EvaluationReleaseGate": (".evaluation.ReleaseGate", "EvaluationReleaseGate"),
    "ReleaseGateResult": (".evaluation.ReleaseGate", "ReleaseGateResult"),
    "evaluate_release_gate": (".evaluation.ReleaseGate", "evaluate_release_gate"),
    "ModelExportRequest": (".runtime.ModelExporter", "ModelExportRequest"),
    "ModelExportResult": (".runtime.ModelExporter", "ModelExportResult"),
    "ModelExporter": (".runtime.ModelExporter", "ModelExporter"),
    "export_model": (".runtime.ModelExporter", "export_model"),
    "InferenceServerSettings": (".runtime.InferenceServer", "InferenceServerSettings"),
    "LocalGenerationEngine": (".runtime.InferenceServer", "LocalGenerationEngine"),
    "create_inference_app": (".runtime.InferenceServer", "create_inference_app"),
    "load_inference_model": (".runtime.InferenceServer", "load_inference_model"),
    "SmokeTestRunner": (".evaluation.SmokeTestRunner", "SmokeTestRunner"),
    "SmokeTestResult": (".evaluation.SmokeTestRunner", "SmokeTestResult"),
    "SmokeCommandResult": (".evaluation.SmokeTestRunner", "SmokeCommandResult"),
    "run_smoke_tests": (".evaluation.SmokeTestRunner", "run_smoke_tests"),
    "ExperimentTracker": (".experiments.ExperimentTracker", "ExperimentTracker"),
    "BenchmarkRunner": (".evaluation.BenchmarkRunner", "BenchmarkRunner"),
    "ScalingLawAnalyzer": (".experiments.ScalingLawAnalyzer", "ScalingLawAnalyzer"),
    "PretrainRunPlan": (".experiments.ScalingLawAnalyzer", "PretrainRunPlan"),
    "CurriculumScheduler": (".experiments.CurriculumScheduler", "CurriculumScheduler"),
    # Advanced training and alignment
    "TrainingMonitor": (".experiments.TrainingMonitor", "TrainingMonitor"),
    "DataMixer": (".data.pipeline", "DataMixer"),
    "GRPOConfig": (".alignment.GRPOTrainer", "GRPOConfig"),
    "GRPOTrainer": (".alignment.GRPOTrainer", "GRPOTrainer"),
    "RLScalingTrainer": (".alignment.RLScaling", "RLScalingTrainer"),
    "RLScalingConfig": (".alignment.RLScaling", "RLScalingConfig"),
    "RolloutBuffer": (".alignment.RLScaling", "RolloutBuffer"),
    "RolloutSample": (".alignment.RLScaling", "RolloutSample"),
    "RolloutSegment": (".alignment.RLScaling", "RolloutSegment"),
    "RewardManager": (".alignment.RLScaling", "RewardManager"),
    "TriageConfig": (".alignment.RLScaling", "TriageConfig"),
    "ActionRoleClassifier": (".alignment.RLScaling", "ActionRoleClassifier"),
    "TriageCreditAssigner": (".alignment.RLScaling", "TriageCreditAssigner"),
    "TriageRolloutProcessor": (".alignment.RLScaling", "TriageRolloutProcessor"),
    "TrainingStrategyAdvisor": (".factory.TrainingStrategyAdvisor", "TrainingStrategyAdvisor"),
    "FeasibilityReport": (".factory.TrainingStrategyAdvisor", "FeasibilityReport"),
    "TrainingRoute": (".factory.TrainingStrategyAdvisor", "TrainingRoute"),
    "BudgetProfile": (".factory.TrainingStrategyAdvisor", "BudgetProfile"),
    "PretrainStabilityCallback": (".experiments.PretrainStability", "PretrainStabilityCallback"),
    "StabilityConfig": (".experiments.PretrainStability", "StabilityConfig"),
    "StabilityEvent": (".experiments.PretrainStability", "StabilityEvent"),
    "CheckpointInspector": (".experiments.PretrainStability", "CheckpointInspector"),
    "DensePretrainer": (".training.DensePretrainer", "DensePretrainer"),
    "init_weights_llama_style": (".training.DensePretrainer", "init_weights_llama_style"),
    "init_weights_deepseek_style": (".training.DensePretrainer", "init_weights_deepseek_style"),
    # Alignment algorithms
    "ConstitutionalAI": (".alignment.FrontierAlign", "ConstitutionalAI"),
    "ProcessRewardModel": (".alignment.FrontierAlign", "ProcessRewardModel"),
    "RejectionSampling": (".alignment.FrontierAlign", "RejectionSampling"),
    "FrontierAlignmentPipeline": (".alignment.FrontierAlign", "FrontierAlignmentPipeline"),
    # Training quality techniques
    "EMA": (".alignment.AdvancedTechniques", "EMA"),
    "EMACallback": (".alignment.AdvancedTechniques", "EMACallback"),
    "SelfConsistency": (".alignment.AdvancedTechniques", "SelfConsistency"),
    "EvolInstruct": (".alignment.AdvancedTechniques", "EvolInstruct"),
    "ModelSoup": (".alignment.AdvancedTechniques", "ModelSoup"),
    "InstructionBacktranslation": (".alignment.AdvancedTechniques", "InstructionBacktranslation"),
    # Experimental architectures and alignment
    "MultiTokenPredictionHead": (".alignment.ExclusiveTechniques", "MultiTokenPredictionHead"),
    "MultiTokenPredictionLoss": (".alignment.ExclusiveTechniques", "MultiTokenPredictionLoss"),
    "add_mtp_to_model": (".alignment.ExclusiveTechniques", "add_mtp_to_model"),
    "AuxLossFreeRouter": (".alignment.ExclusiveTechniques", "AuxLossFreeRouter"),
    "AuxLossFreeMoELayer": (".alignment.ExclusiveTechniques", "AuxLossFreeMoELayer"),
    "IterativeAlignment": (".alignment.ExclusiveTechniques", "IterativeAlignment"),
    "TestTimeCompute": (".alignment.ExclusiveTechniques", "TestTimeCompute"),
    "RLAIF": (".alignment.ExclusiveTechniques", "RLAIF"),
    "SLURPMixer": (".alignment.ExclusiveTechniques", "SLURPMixer"),
    "RoPEScaling": (".alignment.ExclusiveTechniques", "RoPEScaling"),
    "SparseAutoencoder": (".alignment.ExclusiveTechniques", "SparseAutoencoder"),
    # Distillation
    "TeacherInterface": (".distillation.UniversalDistiller", "TeacherInterface"),
    "DataDistiller": (".distillation.UniversalDistiller", "DataDistiller"),
    "MultiTeacherDistiller": (".distillation.UniversalDistiller", "MultiTeacherDistiller"),
    "CapabilityDistiller": (".distillation.UniversalDistiller", "CapabilityDistiller"),
    "AutoDistiller": (".distillation.UniversalDistiller", "AutoDistiller"),
    "DistillConfig": (".distillation.UniversalDistiller", "DistillConfig"),
    "OnPolicyTeacherSpec": (".distillation.OnPolicyDistillation", "OnPolicyTeacherSpec"),
    "TeacherPolicySignal": (".distillation.OnPolicyDistillation", "TeacherPolicySignal"),
    "MOPDConfig": (".distillation.OnPolicyDistillation", "MOPDConfig"),
    "MultiTeacherOnPolicyDistiller": (
        ".distillation.OnPolicyDistillation",
        "MultiTeacherOnPolicyDistiller",
    ),
    # Convenience data tools
    "easy": (".easy", None),
    "DataCatalog": (".data.DataCatalog", "DataCatalog"),
    "DataQualityClassifier": (".data.DataCatalog", "DataQualityClassifier"),
    # UI and deployment
    "ChatUI": (".runtime.ChatUI", "ChatUI"),
    "Deploy": (".runtime.Deploy", "Deploy"),
    # Lightweight inference and distillation
    "Lightweight": (".compression.lightweight", "Lightweight"),
    "RapidDistill": (".distillation.RapidDistill", "RapidDistill"),
    "SmartRouter": (".distillation.RapidDistill", "SmartRouter"),
    "ParallelAPICaller": (".distillation.RapidDistill", "ParallelAPICaller"),
    "TEACHER_PROFILES": (".distillation.RapidDistill", "TEACHER_PROFILES"),
    "DOWNLOADABLE_TEACHERS": (".distillation.RapidDistill", "DOWNLOADABLE_TEACHERS"),
    "ModelDownloader": (".distillation.RapidDistill", "ModelDownloader"),
    "LocalTeacherPool": (".distillation.RapidDistill", "LocalTeacherPool"),
    "quick_local_distill": (".distillation.RapidDistill", "quick_local_distill"),
    # Safe generation
    "SafeGenerate": (".alignment.SafeGenerate", "SafeGenerate"),
    "AntiRepeatGenerator": (".alignment.SafeGenerate", "AntiRepeatGenerator"),
    "OutputSafetyFilter": (".alignment.SafeGenerate", "OutputSafetyFilter"),
    "filter_toxic_texts": (".alignment.SafeGenerate", "filter_toxic_texts"),
    # Training utilities
    "check_environment": (".utils.TrainerUtils", "check_environment"),
    "TrainingDiagnostics": (".utils.TrainerUtils", "TrainingDiagnostics"),
    "TrainingReportCard": (".utils.TrainerUtils", "TrainingReportCard"),
    "EarlyStopping": (".utils.TrainerUtils", "EarlyStopping"),
    "auto_train_best_small_model": (".utils.TrainerUtils", "auto_train_best_small_model"),
}
