"""Versioned multimodal and episode dataset normalization.

The v2 schema keeps the historical ``messages``/``images`` fields while
adding modality-neutral segments and optional world-model transitions:

{
  "messages": [{"role": "user", "content": "<image>\nquestion"}, ...],
  "images": [{"path": "...", "type": "image"}],
  "segments": [
    {"modality": "video", "uri": "...", "role": "target", "start_time": 0.0}
  ],
  "observations": [...], "actions": [...], "rewards": [...], "dones": [...],
  "task": "mllm_sft"
}
"""
import csv
import json
import os
from dataclasses import asdict, dataclass, field
from typing import Any, Dict, Iterable, List, Optional, Sequence


SUPPORTED_MODALITIES = frozenset({"text", "image", "audio", "video"})
SUPPORTED_SEGMENT_ROLES = frozenset({"input", "target", "observation", "context"})


@dataclass
class MultimodalSegment:
    """One time-addressable item consumed or generated by a model."""

    modality: str
    role: str = "input"
    uri: Optional[str] = None
    text: Optional[str] = None
    start_time: Optional[float] = None
    end_time: Optional[float] = None
    codec: Optional[str] = None
    metadata: Dict = field(default_factory=dict)

    def __post_init__(self) -> None:
        self.modality = str(self.modality).lower()
        self.role = str(self.role).lower()
        if self.modality not in SUPPORTED_MODALITIES:
            raise ValueError(
                f"Unsupported segment modality {self.modality!r}; expected one of "
                + ", ".join(sorted(SUPPORTED_MODALITIES))
            )
        if self.role not in SUPPORTED_SEGMENT_ROLES:
            raise ValueError(
                f"Unsupported segment role {self.role!r}; expected one of "
                + ", ".join(sorted(SUPPORTED_SEGMENT_ROLES))
            )
        if self.modality == "text" and not self.text:
            raise ValueError("Text segments require non-empty text")
        if self.modality != "text" and not self.uri:
            raise ValueError(f"{self.modality} segments require uri")
        if self.start_time is not None and self.start_time < 0:
            raise ValueError("segment start_time cannot be negative")
        if (
            self.start_time is not None
            and self.end_time is not None
            and self.end_time < self.start_time
        ):
            raise ValueError("segment end_time cannot be earlier than start_time")

    def to_dict(self) -> Dict:
        return {
            key: value
            for key, value in asdict(self).items()
            if value is not None and (key != "metadata" or value)
        }


@dataclass
class MultimodalAsset:
    path: str
    type: str = "image"
    metadata: Dict = field(default_factory=dict)

    def to_dict(self) -> Dict:
        return asdict(self)

    def to_segment(self, *, role: str = "input") -> MultimodalSegment:
        timing = dict(self.metadata or {})
        return MultimodalSegment(
            modality=self.type,
            role=role,
            uri=self.path,
            start_time=timing.pop("start_time", timing.pop("start", None)),
            end_time=timing.pop("end_time", timing.pop("end", None)),
            codec=timing.pop("codec", None),
            metadata=timing,
        )


@dataclass
class MultimodalSample:
    messages: List[Dict[str, str]]
    images: List[MultimodalAsset] = field(default_factory=list)
    segments: List[MultimodalSegment] = field(default_factory=list)
    observations: List[Any] = field(default_factory=list)
    actions: List[Any] = field(default_factory=list)
    rewards: List[float] = field(default_factory=list)
    dones: List[bool] = field(default_factory=list)
    timestamps: List[float] = field(default_factory=list)
    task: str = "mllm_sft"
    sample_id: Optional[str] = None
    provenance: Dict = field(default_factory=dict)
    license: Optional[str] = None
    metadata: Dict = field(default_factory=dict)
    schema_version: int = 2

    def to_dict(self) -> Dict:
        payload = {
            "schema_version": self.schema_version,
            "messages": self.messages,
            "images": [image.to_dict() for image in self.images],
            "segments": [segment.to_dict() for segment in self.segments],
            "task": self.task,
            "metadata": self.metadata,
        }
        for key in ("observations", "actions", "rewards", "dones", "timestamps"):
            value = getattr(self, key)
            if value:
                payload[key] = value
        if self.sample_id is not None:
            payload["sample_id"] = self.sample_id
        if self.provenance:
            payload["provenance"] = self.provenance
        if self.license is not None:
            payload["license"] = self.license
        return payload

    def validate_episode(self) -> None:
        """Validate aligned transition fields when episode data is present."""

        if self.actions and self.observations and len(self.observations) != len(self.actions) + 1:
            raise ValueError(
                "episode observations length must equal actions length + 1"
            )
        if self.rewards and len(self.rewards) != len(self.actions):
            raise ValueError("episode rewards must have the same length as actions")
        if self.dones and len(self.dones) != len(self.actions):
            raise ValueError("episode dones must have the same length as actions")
        if self.timestamps and len(self.timestamps) not in {
            len(self.actions),
            len(self.actions) + 1,
        }:
            raise ValueError(
                "episode timestamps must align with actions or observation boundaries"
            )


@dataclass
class MultimodalNormalizationReport:
    input_path: Optional[str] = None
    output_path: Optional[str] = None
    total_records: int = 0
    kept_records: int = 0
    dropped_records: int = 0
    detected_schemas: Dict[str, int] = field(default_factory=dict)
    modality_counts: Dict[str, int] = field(default_factory=dict)
    warnings: List[str] = field(default_factory=list)

    def to_dict(self) -> Dict:
        return asdict(self)


class MultimodalDataAdapter:
    """Normalize chat, generative multimodal, and episode-style records."""

    IMAGE_TOKEN = "<image>"
    MODALITY_TOKENS = {
        "image": "<image>",
        "audio": "<audio>",
        "video": "<video>",
    }

    @classmethod
    def normalize_record(
        cls,
        record: Dict,
        image_root: Optional[str] = None,
        task: str = "mllm_sft",
    ) -> Optional[MultimodalSample]:
        segments = cls._extract_segments(record, media_root=image_root)
        raw_observations = record.get(
            "observations", record.get("obs", record.get("states", []))
        )
        observations = [] if raw_observations is None else list(raw_observations)
        images = [
            MultimodalAsset(
                path=str(segment.uri),
                type="image",
                metadata={
                    **segment.metadata,
                    **({"start_time": segment.start_time} if segment.start_time is not None else {}),
                    **({"end_time": segment.end_time} if segment.end_time is not None else {}),
                    **({"codec": segment.codec} if segment.codec else {}),
                },
            )
            for segment in segments
            if segment.modality == "image" and segment.uri
        ]
        messages = cls._extract_messages(record)
        if not messages:
            question = cls._first(record, ["question", "prompt", "instruction", "query", "input"])
            answer = cls._first(record, ["answer", "output", "response", "completion", "target"])
            if not question and not segments and not observations:
                return None
            user_content = str(question or "")
            input_tokens = [
                cls.MODALITY_TOKENS[segment.modality]
                for segment in segments
                if segment.role in {"input", "observation", "context"}
                and segment.modality in cls.MODALITY_TOKENS
            ]
            if input_tokens:
                user_content = "\n".join([*input_tokens, user_content]).strip()
            messages = [{"role": "user", "content": user_content}]
            if answer:
                messages.append({"role": "assistant", "content": str(answer)})
        input_modalities = {
            segment.modality
            for segment in segments
            if segment.role in {"input", "observation", "context"}
        }
        for modality in sorted(input_modalities):
            token = cls.MODALITY_TOKENS.get(modality)
            if not token or any(token in message.get("content", "") for message in messages):
                continue
            for message in messages:
                if message.get("role") == "user":
                    message["content"] = f"{token}\n{message.get('content', '')}".strip()
                    break
        if not segments and not (task == "world_dynamics" and observations):
            return None
        requires_assistant = task in {"mllm_sft", "vision_alignment", "vla_sft"}
        if requires_assistant and not any(message.get("role") == "assistant" for message in messages):
            return None
        metadata = dict(record.get("metadata", {})) if isinstance(record.get("metadata"), dict) else {}
        for key in ("source", "dataset", "domain", "category"):
            if key in record:
                metadata[key] = record[key]
        provenance = (
            dict(record.get("provenance", {}))
            if isinstance(record.get("provenance"), dict)
            else {}
        )
        actions = list(record.get("actions", []))
        if not actions and record.get("action") is not None:
            actions = [record["action"]]
        rewards = [float(value) for value in record.get("rewards", [])]
        if not rewards and record.get("reward") is not None:
            rewards = [float(record["reward"])]
        dones = [bool(value) for value in record.get("dones", [])]
        if not dones and record.get("done") is not None:
            dones = [bool(record["done"])]
        sample = MultimodalSample(
            messages=messages,
            images=images,
            segments=segments,
            observations=observations,
            actions=actions,
            rewards=rewards,
            dones=dones,
            timestamps=[float(value) for value in record.get("timestamps", [])],
            task=task,
            sample_id=str(record.get("sample_id", record.get("id"))) if record.get("sample_id", record.get("id")) is not None else None,
            provenance=provenance,
            license=str(record["license"]) if record.get("license") is not None else None,
            metadata=metadata,
        )
        sample.validate_episode()
        return sample

    @classmethod
    def normalize_records(
        cls,
        records: Iterable[Dict],
        image_root: Optional[str] = None,
        task: str = "mllm_sft",
    ) -> (List[MultimodalSample], MultimodalNormalizationReport):
        samples: List[MultimodalSample] = []
        report = MultimodalNormalizationReport()
        for record in records:
            report.total_records += 1
            schema = cls.detect_schema(record)
            report.detected_schemas[schema] = report.detected_schemas.get(schema, 0) + 1
            sample = cls.normalize_record(record, image_root=image_root, task=task)
            if sample is None:
                report.dropped_records += 1
                continue
            samples.append(sample)
            report.kept_records += 1
            for segment in sample.segments:
                report.modality_counts[segment.modality] = (
                    report.modality_counts.get(segment.modality, 0) + 1
                )
        if report.kept_records == 0:
            report.warnings.append("No multimodal records survived normalization.")
        return samples, report

    @classmethod
    def normalize_file(
        cls,
        input_path: str,
        output_path: str,
        image_root: Optional[str] = None,
        task: str = "mllm_sft",
    ) -> MultimodalNormalizationReport:
        records = cls.load_records(input_path)
        samples, report = cls.normalize_records(records, image_root=image_root or os.path.dirname(input_path), task=task)
        os.makedirs(os.path.dirname(output_path) or ".", exist_ok=True)
        with open(output_path, "w", encoding="utf-8") as f:
            for sample in samples:
                f.write(json.dumps(sample.to_dict(), ensure_ascii=False) + "\n")
        report.input_path = input_path
        report.output_path = output_path
        with open(output_path + ".report.json", "w", encoding="utf-8") as f:
            json.dump(report.to_dict(), f, ensure_ascii=False, indent=2)
        return report

    @staticmethod
    def load_records(path: str) -> List[Dict]:
        ext = os.path.splitext(path)[1].lower()
        if ext == ".jsonl":
            records = []
            with open(path, "r", encoding="utf-8") as f:
                for line in f:
                    line = line.strip()
                    if line:
                        records.append(json.loads(line))
            return records
        if ext == ".json":
            with open(path, "r", encoding="utf-8") as f:
                data = json.load(f)
            if isinstance(data, list):
                return data
            for key in ("data", "train", "annotations", "examples", "instances"):
                if isinstance(data.get(key), list):
                    return data[key]
            return [data]
        if ext == ".csv":
            with open(path, "r", encoding="utf-8", newline="") as f:
                return list(csv.DictReader(f))
        raise ValueError(f"Unsupported multimodal data file: {path}")

    @staticmethod
    def detect_schema(record: Dict) -> str:
        if "segments" in record:
            return "unified_multimodal_v2"
        if any(key in record for key in ("audio", "audios", "video", "videos")):
            return "generative_media"
        if "messages" in record and ("images" in record or "image" in record):
            return "mllm_messages"
        if "conversations" in record and ("image" in record or "images" in record):
            return "llava_sharegpt"
        if "question" in record and ("answer" in record or "answers" in record):
            return "vqa"
        if "ocr" in record or "bbox" in record:
            return "document_or_grounding"
        return "unknown"

    @classmethod
    def _extract_messages(cls, record: Dict) -> List[Dict[str, str]]:
        raw = record.get("messages") or record.get("conversations") or record.get("conversation")
        if not raw:
            return []
        messages = []
        for item in raw:
            role = str(item.get("role", item.get("from", item.get("speaker", "user")))).lower()
            if role in {"human", "prompter"}:
                role = "user"
            if role in {"gpt", "bot", "model"}:
                role = "assistant"
            content = str(item.get("content", item.get("value", item.get("text", ""))) or "").strip()
            if role and content:
                messages.append({"role": role, "content": content})
        return messages

    @classmethod
    def _extract_images(cls, record: Dict, image_root: Optional[str]) -> List[MultimodalAsset]:
        return [
            MultimodalAsset(path=str(segment.uri), type="image", metadata=segment.metadata)
            for segment in cls._extract_segments(record, media_root=image_root)
            if segment.modality == "image" and segment.uri
        ]

    @classmethod
    def _extract_segments(
        cls, record: Dict, media_root: Optional[str]
    ) -> List[MultimodalSegment]:
        segments: List[MultimodalSegment] = []
        raw_segments = record.get("segments")
        if raw_segments is not None:
            if not isinstance(raw_segments, list):
                raise ValueError("segments must be a list")
            for item in raw_segments:
                if not isinstance(item, dict):
                    raise ValueError("each segment must be a mapping")
                modality = str(item.get("modality", item.get("type", ""))).lower()
                uri = item.get("uri", item.get("path", item.get("url")))
                if uri:
                    uri = cls._resolve_media_path(str(uri), media_root)
                known = {
                    "modality", "type", "role", "uri", "path", "url", "text",
                    "start_time", "start", "end_time", "end", "codec", "metadata",
                }
                metadata = dict(item.get("metadata", {})) if isinstance(item.get("metadata"), dict) else {}
                metadata.update({key: value for key, value in item.items() if key not in known})
                segments.append(MultimodalSegment(
                    modality=modality,
                    role=item.get("role", "input"),
                    uri=uri,
                    text=item.get("text"),
                    start_time=item.get("start_time", item.get("start")),
                    end_time=item.get("end_time", item.get("end")),
                    codec=item.get("codec"),
                    metadata=metadata,
                ))
            return segments

        aliases = {
            "image": ("images", "image", "image_path", "image_file"),
            "audio": ("audios", "audio", "audio_path", "audio_file"),
            "video": ("videos", "video", "video_path", "video_file"),
        }
        target_modality = str(record.get("target_modality", "")).lower()
        for modality, keys in aliases.items():
            raw_items = next((record[key] for key in keys if record.get(key) is not None), None)
            if raw_items is None:
                continue
            if isinstance(raw_items, (str, dict)):
                raw_items = [raw_items]
            for item in raw_items:
                metadata: Dict[str, Any] = {}
                role = "target" if target_modality == modality else "input"
                if isinstance(item, dict):
                    uri = item.get(
                        "uri",
                        item.get("path", item.get(modality, item.get("file_name", item.get("url")))),
                    )
                    role = item.get("role", role)
                    known = {
                        "uri", "path", modality, "file_name", "url", "role",
                        "start_time", "start", "end_time", "end", "codec", "metadata",
                    }
                    metadata = dict(item.get("metadata", {})) if isinstance(item.get("metadata"), dict) else {}
                    metadata.update({key: value for key, value in item.items() if key not in known})
                    start_time = item.get("start_time", item.get("start"))
                    end_time = item.get("end_time", item.get("end"))
                    codec = item.get("codec")
                else:
                    uri = str(item)
                    start_time = end_time = codec = None
                if not uri:
                    continue
                segments.append(MultimodalSegment(
                    modality=modality,
                    role=role,
                    uri=cls._resolve_media_path(str(uri), media_root),
                    start_time=start_time,
                    end_time=end_time,
                    codec=codec,
                    metadata=metadata,
                ))
        return segments

    @staticmethod
    def _resolve_media_path(path: str, media_root: Optional[str]) -> str:
        if media_root and not os.path.isabs(path) and not path.startswith(
            ("http://", "https://", "s3://", "gs://", "hf://")
        ):
            return os.path.abspath(os.path.join(media_root, path))
        return path

    @staticmethod
    def _first(record: Dict, keys: Sequence[str]) -> str:
        for key in keys:
            value = record.get(key)
            if isinstance(value, list) and value:
                value = value[0]
            if value not in (None, ""):
                return str(value)
        return ""


def normalize_multimodal_file(
    input_path: str,
    output_path: str,
    image_root: Optional[str] = None,
    task: str = "mllm_sft",
) -> Dict:
    return MultimodalDataAdapter.normalize_file(
        input_path=input_path,
        output_path=output_path,
        image_root=image_root,
        task=task,
    ).to_dict()
